#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace TownePark
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_ActionOverrides"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_ActionOverrides> bs_ActionOverridesSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_ActionOverrides>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_BellService"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_BellService> bs_BellServiceSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_BellService>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_BillableAccount"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_BillableAccount> bs_BillableAccountSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_BillableAccount>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_BillingStatement"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_BillingStatement> bs_BillingStatementSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_BillingStatement>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_Contract"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_Contract> bs_ContractSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_Contract>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_CustomerSite"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_CustomerSite> bs_CustomerSiteSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_CustomerSite>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_CustomerSitesByUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_CustomerSitesByUser> bs_CustomerSitesByUserSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_CustomerSitesByUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_DepositedRevenue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_DepositedRevenue> bs_DepositedRevenueSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_DepositedRevenue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_EmailGenerationProcess"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_EmailGenerationProcess> bs_EmailGenerationProcessSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_EmailGenerationProcess>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_FixedFeeService"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_FixedFeeService> bs_FixedFeeServiceSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_FixedFeeService>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_ForecastJobProfileMapping"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_ForecastJobProfileMapping> bs_ForecastJobProfileMappingSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_ForecastJobProfileMapping>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_GeneralConfig"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_GeneralConfig> bs_GeneralConfigSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_GeneralConfig>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_GLCodeConfig"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_GLCodeConfig> bs_GLCodeConfigSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_GLCodeConfig>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_Invoice"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_Invoice> bs_InvoiceSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_Invoice>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_InvoiceGroup"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_InvoiceGroup> bs_InvoiceGroupSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_InvoiceGroup>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_JobCode"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_JobCode> bs_JobCodeSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_JobCode>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_JobCodesBySite"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_JobCodesBySite> bs_JobCodesBySiteSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_JobCodesBySite>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_JobGroup"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_JobGroup> bs_JobGroupSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_JobGroup>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_LaborHourJob"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_LaborHourJob> bs_LaborHourJobSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_LaborHourJob>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_ManagementAgreement"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_ManagementAgreement> bs_ManagementAgreementSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_ManagementAgreement>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_MasterCustomerSite"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_MasterCustomerSite> bs_MasterCustomerSiteSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_MasterCustomerSite>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_MidMonthAdvance"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_MidMonthAdvance> bs_MidMonthAdvanceSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_MidMonthAdvance>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_NonGLExpense"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_NonGLExpense> bs_NonGLExpenseSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_NonGLExpense>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_OtherExpenseDetail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_OtherExpenseDetail> bs_OtherExpenseDetailSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_OtherExpenseDetail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_OtherRevenue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_OtherRevenue> bs_OtherRevenueSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_OtherRevenue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_OtherRevenueDetail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_OtherRevenueDetail> bs_OtherRevenueDetailSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_OtherRevenueDetail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_ParkingRate"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_ParkingRate> bs_ParkingRateSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_ParkingRate>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_ParkingRateDetail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_ParkingRateDetail> bs_ParkingRateDetailSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_ParkingRateDetail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_Payroll"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_Payroll> bs_PayrollSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_Payroll>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_PayrollDetail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_PayrollDetail> bs_PayrollDetailSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_PayrollDetail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_ProfitShareByPercentage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_ProfitShareByPercentage> bs_ProfitShareByPercentageSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_ProfitShareByPercentage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_ResourceLock"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_ResourceLock> bs_ResourceLockSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_ResourceLock>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_RevenueShareThreshold"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_RevenueShareThreshold> bs_RevenueShareThresholdSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_RevenueShareThreshold>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_SiteStatistic"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_SiteStatistic> bs_SiteStatisticSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_SiteStatistic>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_SiteStatisticDetail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_SiteStatisticDetail> bs_SiteStatisticDetailSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_SiteStatisticDetail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_StatementGenerationProcess"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_StatementGenerationProcess> bs_StatementGenerationProcessSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_StatementGenerationProcess>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_UnitAccountBatchProcess"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_UnitAccountBatchProcess> bs_UnitAccountBatchProcessSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_UnitAccountBatchProcess>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.bs_User"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.bs_User> bs_UserSet
		{
			get
			{
				return this.CreateQuery<TownePark.bs_User>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TownePark.cr9e8_readyforinvoice"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TownePark.cr9e8_readyforinvoice> cr9e8_readyforinvoiceSet
		{
			get
			{
				return this.CreateQuery<TownePark.cr9e8_readyforinvoice>();
			}
		}
	}
}
#pragma warning restore CS1591
