#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Billing Statement
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_billingstatement_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Billing Statement
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_billingstatement_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_billingstatement")]
	public partial class bs_BillingStatement : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_billingstatement entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_BillingStatementId = "bs_billingstatementid";
			public const string Id = "bs_billingstatementid";
			public const string bs_CustomerSiteFK = "bs_customersitefk";
			public const string bs_ForecastData = "bs_forecastdata";
			public const string bs_Name = "bs_name";
			public const string bs_PurchaseOrder = "bs_purchaseorder";
			public const string bs_ServicePeriodEnd = "bs_serviceperiodend";
			public const string bs_ServicePeriodStart = "bs_serviceperiodstart";
			public const string bs_StatementStatus = "bs_statementstatus";
			public const string bs_StatementVersionNumber = "bs_statementversionnumber";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_BillingStatement_cr9e8_readyforinvoice = "bs_BillingStatement_cr9e8_readyforinvoice";
			public const string bs_EmailGenerationProcess_BillingStatement = "bs_EmailGenerationProcess_BillingStatement";
			public const string bs_Invoice_BillingStatement = "bs_Invoice_BillingStatement";
			public const string bs_BillingStatement_CustomerSite = "bs_BillingStatement_CustomerSite";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_BillingStatement() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_billingstatement";
		
		public const string EntityLogicalCollectionName = "bs_billingstatements";
		
		public const string EntitySetName = "bs_billingstatements";
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingstatementid")]
		public System.Nullable<System.Guid> bs_BillingStatementId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_billingstatementid");
			}
			set
			{
				this.SetAttributeValue("bs_billingstatementid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingstatementid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_BillingStatementId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_CustomerSiteFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_customersitefk");
			}
			set
			{
				this.SetAttributeValue("bs_customersitefk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_forecastdata")]
		public string bs_ForecastData
		{
			get
			{
				return this.GetAttributeValue<string>("bs_forecastdata");
			}
			set
			{
				this.SetAttributeValue("bs_forecastdata", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		/// <summary>
		/// contract's PO Number at the time of Statement Generation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_purchaseorder")]
		public string bs_PurchaseOrder
		{
			get
			{
				return this.GetAttributeValue<string>("bs_purchaseorder");
			}
			set
			{
				this.SetAttributeValue("bs_purchaseorder", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_serviceperiodend")]
		public System.Nullable<System.DateTime> bs_ServicePeriodEnd
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_serviceperiodend");
			}
			set
			{
				this.SetAttributeValue("bs_serviceperiodend", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_serviceperiodstart")]
		public System.Nullable<System.DateTime> bs_ServicePeriodStart
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_serviceperiodstart");
			}
			set
			{
				this.SetAttributeValue("bs_serviceperiodstart", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_statementstatus")]
		public virtual bs_billingstatementstatuschoices? bs_StatementStatus
		{
			get
			{
				return ((bs_billingstatementstatuschoices?)(EntityOptionSetEnum.GetEnum(this, "bs_statementstatus")));
			}
			set
			{
				this.SetAttributeValue("bs_statementstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_statementversionnumber")]
		public System.Nullable<int> bs_StatementVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_statementversionnumber");
			}
			set
			{
				this.SetAttributeValue("bs_statementversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Billing Statement
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_billingstatement_statecode? statecode
		{
			get
			{
				return ((bs_billingstatement_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Billing Statement
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_billingstatement_statuscode? statuscode
		{
			get
			{
				return ((bs_billingstatement_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bs_BillingStatement_cr9e8_readyforinvoice
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_BillingStatement_cr9e8_readyforinvoice")]
		public System.Collections.Generic.IEnumerable<TownePark.cr9e8_readyforinvoice> bs_BillingStatement_cr9e8_readyforinvoice
		{
			get
			{
				return this.GetRelatedEntities<TownePark.cr9e8_readyforinvoice>("bs_BillingStatement_cr9e8_readyforinvoice", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.cr9e8_readyforinvoice>("bs_BillingStatement_cr9e8_readyforinvoice", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_EmailGenerationProcess_BillingStatement
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_EmailGenerationProcess_BillingStatement")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_EmailGenerationProcess> bs_EmailGenerationProcess_BillingStatement
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_EmailGenerationProcess>("bs_EmailGenerationProcess_BillingStatement", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_EmailGenerationProcess>("bs_EmailGenerationProcess_BillingStatement", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_Invoice_BillingStatement
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_Invoice_BillingStatement")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_Invoice> bs_Invoice_BillingStatement
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_Invoice>("bs_Invoice_BillingStatement", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_Invoice>("bs_Invoice_BillingStatement", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bs_BillingStatement_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_BillingStatement_CustomerSite")]
		public TownePark.bs_CustomerSite bs_BillingStatement_CustomerSite
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_CustomerSite>("bs_BillingStatement_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_CustomerSite>("bs_BillingStatement_CustomerSite", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
