#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Billable Account
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_billableaccount_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Billable Account
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_billableaccount_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_billableaccount")]
	public partial class bs_BillableAccount : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_billableaccount entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_AdditionalPayrollAmount = "bs_additionalpayrollamount";
			public const string bs_BillableAccountId = "bs_billableaccountid";
			public const string Id = "bs_billableaccountid";
			public const string bs_ContractFK = "bs_contractfk";
			public const string bs_ExpenseAccountsData = "bs_expenseaccountsdata";
			public const string bs_ExpenseAccountsInvoiceGroup = "bs_expenseaccountsinvoicegroup";
			public const string bs_ExpenseAccountsLineTitle = "bs_expenseaccountslinetitle";
			public const string bs_Name = "bs_name";
			public const string bs_PayrollAccountsData = "bs_payrollaccountsdata";
			public const string bs_PayrollAccountsInvoiceGroup = "bs_payrollaccountsinvoicegroup";
			public const string bs_PayrollAccountsLineTitle = "bs_payrollaccountslinetitle";
			public const string bs_PayrollSupportAmount = "bs_payrollsupportamount";
			public const string bs_PayrollSupportBillingType = "bs_payrollsupportbillingtype";
			public const string bs_PayrollSupportEnabled = "bs_payrollsupportenabled";
			public const string bs_PayrollSupportLineTitle = "bs_payrollsupportlinetitle";
			public const string bs_PayrollSupportPayrollType = "bs_payrollsupportpayrolltype";
			public const string bs_PayrollTaxesBillingType = "bs_payrolltaxesbillingtype";
			public const string bs_PayrollTaxesEnabled = "bs_payrolltaxesenabled";
			public const string bs_PayrollTaxesEscalatorEnable = "bs_payrolltaxesescalatorenable";
			public const string bs_PayrollTaxesEscalatorMonth = "bs_payrolltaxesescalatormonth";
			public const string bs_PayrollTaxesEscalatorType = "bs_payrolltaxesescalatortype";
			public const string bs_PayrollTaxesEscalatorvalue = "bs_payrolltaxesescalatorvalue";
			public const string bs_PayrollTaxesLineTitle = "bs_payrolltaxeslinetitle";
			public const string bs_PayrollTaxesPercentage = "bs_payrolltaxespercentage";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_BillableAccount_Contract = "bs_BillableAccount_Contract";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_BillableAccount() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_billableaccount";
		
		public const string EntityLogicalCollectionName = "bs_billableaccounts";
		
		public const string EntitySetName = "bs_billableaccounts";
		
		/// <summary>
		/// Additional Payroll Amount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_additionalpayrollamount")]
		public System.Nullable<decimal> bs_AdditionalPayrollAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_additionalpayrollamount");
			}
			set
			{
				this.SetAttributeValue("bs_additionalpayrollamount", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billableaccountid")]
		public System.Nullable<System.Guid> bs_BillableAccountId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_billableaccountid");
			}
			set
			{
				this.SetAttributeValue("bs_billableaccountid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billableaccountid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_BillableAccountId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_ContractFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_contractfk");
			}
			set
			{
				this.SetAttributeValue("bs_contractfk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_expenseaccountsdata")]
		public string bs_ExpenseAccountsData
		{
			get
			{
				return this.GetAttributeValue<string>("bs_expenseaccountsdata");
			}
			set
			{
				this.SetAttributeValue("bs_expenseaccountsdata", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_expenseaccountsinvoicegroup")]
		public System.Nullable<int> bs_ExpenseAccountsInvoiceGroup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_expenseaccountsinvoicegroup");
			}
			set
			{
				this.SetAttributeValue("bs_expenseaccountsinvoicegroup", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_expenseaccountslinetitle")]
		public string bs_ExpenseAccountsLineTitle
		{
			get
			{
				return this.GetAttributeValue<string>("bs_expenseaccountslinetitle");
			}
			set
			{
				this.SetAttributeValue("bs_expenseaccountslinetitle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollaccountsdata")]
		public string bs_PayrollAccountsData
		{
			get
			{
				return this.GetAttributeValue<string>("bs_payrollaccountsdata");
			}
			set
			{
				this.SetAttributeValue("bs_payrollaccountsdata", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollaccountsinvoicegroup")]
		public System.Nullable<int> bs_PayrollAccountsInvoiceGroup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_payrollaccountsinvoicegroup");
			}
			set
			{
				this.SetAttributeValue("bs_payrollaccountsinvoicegroup", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollaccountslinetitle")]
		public string bs_PayrollAccountsLineTitle
		{
			get
			{
				return this.GetAttributeValue<string>("bs_payrollaccountslinetitle");
			}
			set
			{
				this.SetAttributeValue("bs_payrollaccountslinetitle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollsupportamount")]
		public System.Nullable<decimal> bs_PayrollSupportAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_payrollsupportamount");
			}
			set
			{
				this.SetAttributeValue("bs_payrollsupportamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollsupportbillingtype")]
		public virtual bs_supportservices? bs_PayrollSupportBillingType
		{
			get
			{
				return ((bs_supportservices?)(EntityOptionSetEnum.GetEnum(this, "bs_payrollsupportbillingtype")));
			}
			set
			{
				this.SetAttributeValue("bs_payrollsupportbillingtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollsupportenabled")]
		public System.Nullable<bool> bs_PayrollSupportEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_payrollsupportenabled");
			}
			set
			{
				this.SetAttributeValue("bs_payrollsupportenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollsupportlinetitle")]
		public string bs_PayrollSupportLineTitle
		{
			get
			{
				return this.GetAttributeValue<string>("bs_payrollsupportlinetitle");
			}
			set
			{
				this.SetAttributeValue("bs_payrollsupportlinetitle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollsupportpayrolltype")]
		public virtual bs_supportpayroll? bs_PayrollSupportPayrollType
		{
			get
			{
				return ((bs_supportpayroll?)(EntityOptionSetEnum.GetEnum(this, "bs_payrollsupportpayrolltype")));
			}
			set
			{
				this.SetAttributeValue("bs_payrollsupportpayrolltype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxesbillingtype")]
		public virtual bs_ptebbillingtype? bs_PayrollTaxesBillingType
		{
			get
			{
				return ((bs_ptebbillingtype?)(EntityOptionSetEnum.GetEnum(this, "bs_payrolltaxesbillingtype")));
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxesbillingtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxesenabled")]
		public System.Nullable<bool> bs_PayrollTaxesEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_payrolltaxesenabled");
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxesenabled", value);
			}
		}
		
		/// <summary>
		///  Payroll Taxes Escalator Enable
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxesescalatorenable")]
		public System.Nullable<bool> bs_PayrollTaxesEscalatorEnable
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_payrolltaxesescalatorenable");
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxesescalatorenable", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxesescalatormonth")]
		public System.Nullable<int> bs_PayrollTaxesEscalatorMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_payrolltaxesescalatormonth");
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxesescalatormonth", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxesescalatortype")]
		public virtual bs_escalatortype? bs_PayrollTaxesEscalatorType
		{
			get
			{
				return ((bs_escalatortype?)(EntityOptionSetEnum.GetEnum(this, "bs_payrolltaxesescalatortype")));
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxesescalatortype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxesescalatorvalue")]
		public System.Nullable<decimal> bs_PayrollTaxesEscalatorvalue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_payrolltaxesescalatorvalue");
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxesescalatorvalue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxeslinetitle")]
		public string bs_PayrollTaxesLineTitle
		{
			get
			{
				return this.GetAttributeValue<string>("bs_payrolltaxeslinetitle");
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxeslinetitle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolltaxespercentage")]
		public System.Nullable<decimal> bs_PayrollTaxesPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_payrolltaxespercentage");
			}
			set
			{
				this.SetAttributeValue("bs_payrolltaxespercentage", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Billable Account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_billableaccount_statecode? statecode
		{
			get
			{
				return ((bs_billableaccount_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Billable Account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_billableaccount_statuscode? statuscode
		{
			get
			{
				return ((bs_billableaccount_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_BillableAccount_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_BillableAccount_Contract")]
		public TownePark.bs_Contract bs_BillableAccount_Contract
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_Contract>("bs_BillableAccount_Contract", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_Contract>("bs_BillableAccount_Contract", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
