#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Contract
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_contract_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Contract
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_contract_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Stores type-independent contract data
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_contract")]
	public partial class bs_Contract : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_contract entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_AccountsPayable = "bs_accountspayable";
			public const string bs_BillingType = "bs_billingtype";
			public const string bs_ConsumerPriceIndex = "bs_consumerpriceindex";
			public const string bs_ContractId = "bs_contractid";
			public const string Id = "bs_contractid";
			public const string bs_ContractType = "bs_contracttype";
			public const string bs_ContractTypeString = "bs_contracttypestring";
			public const string bs_CustomerSiteFK = "bs_customersitefk";
			public const string bs_Deposits = "bs_deposits";
			public const string bs_DeviationAmount = "bs_deviationamount";
			public const string bs_DeviationPercentage = "bs_deviationpercentage";
			public const string bs_HoursBackupReport = "bs_hoursbackupreport";
			public const string bs_IncrementAmount = "bs_incrementamount";
			public const string bs_IncrementMonth = "bs_incrementmonth";
			public const string bs_Notes = "bs_notes";
			public const string bs_OccupiedRoomCode = "bs_occupiedroomcode";
			public const string bs_OccupiedRoomInvoiceGroup = "bs_occupiedroominvoicegroup";
			public const string bs_OccupiedRoomRate = "bs_occupiedroomrate";
			public const string bs_PaymentTerms = "bs_paymentterms";
			public const string bs_PurchaseOrder = "bs_purchaseorder";
			public const string bs_SupportingReports = "bs_supportingreports";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_BellService_bs_Contract = "bs_BellService_bs_Contract";
			public const string bs_BillableAccount_Contract = "bs_BillableAccount_Contract";
			public const string bs_DepositedRevenue_Contract = "bs_DepositedRevenue_Contract";
			public const string bs_FixedFeeService_Contract = "bs_FixedFeeService_Contract";
			public const string bs_InvoiceGroup_Contract = "bs_InvoiceGroup_Contract";
			public const string bs_LaborHourJob_Contract = "bs_LaborHourJob_Contract";
			public const string bs_ManagementAgreement_Contract = "bs_ManagementAgreement_Contract";
			public const string bs_MidMonthAdvance_bs_Contract = "bs_MidMonthAdvance_bs_Contract";
			public const string bs_nonglexpense_ContractFK_bs_contract = "bs_nonglexpense_ContractFK_bs_contract";
			public const string bs_RevenueShareThreshold_Contract = "bs_RevenueShareThreshold_Contract";
			public const string bs_StatementGenerationProcess_Contract = "bs_StatementGenerationProcess_Contract";
			public const string bs_Contract_CustomerSite = "bs_Contract_CustomerSite";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_Contract() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_contract";
		
		public const string EntityLogicalCollectionName = "bs_contracts";
		
		public const string EntitySetName = "bs_contracts";
		
		/// <summary>
		/// Editable string. By Default: "Attn: Accounts Payable"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_accountspayable")]
		public string bs_AccountsPayable
		{
			get
			{
				return this.GetAttributeValue<string>("bs_accountspayable");
			}
			set
			{
				this.SetAttributeValue("bs_accountspayable", value);
			}
		}
		
		/// <summary>
		/// Advanced or Arrears
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingtype")]
		public virtual bs_billingtypechoices? bs_BillingType
		{
			get
			{
				return ((bs_billingtypechoices?)(EntityOptionSetEnum.GetEnum(this, "bs_billingtype")));
			}
			set
			{
				this.SetAttributeValue("bs_billingtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Checked when costs should be increased according to the Consumer Price Index.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_consumerpriceindex")]
		public System.Nullable<bool> bs_ConsumerPriceIndex
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_consumerpriceindex");
			}
			set
			{
				this.SetAttributeValue("bs_consumerpriceindex", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractid")]
		public System.Nullable<System.Guid> bs_ContractId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_contractid");
			}
			set
			{
				this.SetAttributeValue("bs_contractid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_ContractId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contracttype")]
		public virtual System.Collections.Generic.IEnumerable<bs_contracttypechoices> bs_ContractType
		{
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<bs_contracttypechoices>(this, "bs_contracttype");
			}
			set
			{
				this.SetAttributeValue("bs_contracttype", EntityOptionSetEnum.GetMultiEnum(this, "bs_contracttype", value));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contracttypestring")]
		public string bs_ContractTypeString
		{
			get
			{
				return this.GetAttributeValue<string>("bs_contracttypestring");
			}
			set
			{
				this.SetAttributeValue("bs_contracttypestring", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_CustomerSiteFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_customersitefk");
			}
			set
			{
				this.SetAttributeValue("bs_customersitefk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_deposits")]
		public System.Nullable<bool> bs_Deposits
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_deposits");
			}
			set
			{
				this.SetAttributeValue("bs_deposits", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_deviationamount")]
		public System.Nullable<decimal> bs_DeviationAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_deviationamount");
			}
			set
			{
				this.SetAttributeValue("bs_deviationamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_deviationpercentage")]
		public System.Nullable<decimal> bs_DeviationPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_deviationpercentage");
			}
			set
			{
				this.SetAttributeValue("bs_deviationpercentage", value);
			}
		}
		
		/// <summary>
		/// Indicates if contract should include hours backup report.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_hoursbackupreport")]
		public System.Nullable<bool> bs_HoursBackupReport
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_hoursbackupreport");
			}
			set
			{
				this.SetAttributeValue("bs_hoursbackupreport", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_incrementamount")]
		public System.Nullable<decimal> bs_IncrementAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_incrementamount");
			}
			set
			{
				this.SetAttributeValue("bs_incrementamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_incrementmonth")]
		public System.Nullable<int> bs_IncrementMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_incrementmonth");
			}
			set
			{
				this.SetAttributeValue("bs_incrementmonth", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_notes")]
		public string bs_Notes
		{
			get
			{
				return this.GetAttributeValue<string>("bs_notes");
			}
			set
			{
				this.SetAttributeValue("bs_notes", value);
			}
		}
		
		/// <summary>
		/// GL Code for Occupied Room Rate line item
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_occupiedroomcode")]
		public string bs_OccupiedRoomCode
		{
			get
			{
				return this.GetAttributeValue<string>("bs_occupiedroomcode");
			}
			set
			{
				this.SetAttributeValue("bs_occupiedroomcode", value);
			}
		}
		
		/// <summary>
		/// Indicates to which page of the invoice the occupied room line item belongs to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_occupiedroominvoicegroup")]
		public System.Nullable<int> bs_OccupiedRoomInvoiceGroup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_occupiedroominvoicegroup");
			}
			set
			{
				this.SetAttributeValue("bs_occupiedroominvoicegroup", value);
			}
		}
		
		/// <summary>
		/// Rate charged per occupied room when 'Per Occupied Room' building block is enabled.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_occupiedroomrate")]
		public System.Nullable<decimal> bs_OccupiedRoomRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_occupiedroomrate");
			}
			set
			{
				this.SetAttributeValue("bs_occupiedroomrate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_paymentterms")]
		public string bs_PaymentTerms
		{
			get
			{
				return this.GetAttributeValue<string>("bs_paymentterms");
			}
			set
			{
				this.SetAttributeValue("bs_paymentterms", value);
			}
		}
		
		/// <summary>
		/// Purchase order number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_purchaseorder")]
		public string bs_PurchaseOrder
		{
			get
			{
				return this.GetAttributeValue<string>("bs_purchaseorder");
			}
			set
			{
				this.SetAttributeValue("bs_purchaseorder", value);
			}
		}
		
		/// <summary>
		/// a list of enabled report types for the given contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_supportingreports")]
		public virtual System.Collections.Generic.IEnumerable<bs_supportingreporttypes> bs_SupportingReports
		{
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<bs_supportingreporttypes>(this, "bs_supportingreports");
			}
			set
			{
				this.SetAttributeValue("bs_supportingreports", EntityOptionSetEnum.GetMultiEnum(this, "bs_supportingreports", value));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_contract_statecode? statecode
		{
			get
			{
				return ((bs_contract_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_contract_statuscode? statuscode
		{
			get
			{
				return ((bs_contract_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bs_BellService_bs_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_BellService_bs_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_BellService> bs_BellService_bs_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_BellService>("bs_BellService_bs_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_BellService>("bs_BellService_bs_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_BillableAccount_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_BillableAccount_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_BillableAccount> bs_BillableAccount_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_BillableAccount>("bs_BillableAccount_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_BillableAccount>("bs_BillableAccount_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_DepositedRevenue_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_DepositedRevenue_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_DepositedRevenue> bs_DepositedRevenue_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_DepositedRevenue>("bs_DepositedRevenue_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_DepositedRevenue>("bs_DepositedRevenue_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_FixedFeeService_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_FixedFeeService_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_FixedFeeService> bs_FixedFeeService_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_FixedFeeService>("bs_FixedFeeService_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_FixedFeeService>("bs_FixedFeeService_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_InvoiceGroup_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_InvoiceGroup_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_InvoiceGroup> bs_InvoiceGroup_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_InvoiceGroup>("bs_InvoiceGroup_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_InvoiceGroup>("bs_InvoiceGroup_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_LaborHourJob_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_LaborHourJob_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_LaborHourJob> bs_LaborHourJob_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_LaborHourJob>("bs_LaborHourJob_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_LaborHourJob>("bs_LaborHourJob_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_ManagementAgreement_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_ManagementAgreement_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_ManagementAgreement> bs_ManagementAgreement_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_ManagementAgreement>("bs_ManagementAgreement_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_ManagementAgreement>("bs_ManagementAgreement_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_MidMonthAdvance_bs_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_MidMonthAdvance_bs_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_MidMonthAdvance> bs_MidMonthAdvance_bs_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_MidMonthAdvance>("bs_MidMonthAdvance_bs_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_MidMonthAdvance>("bs_MidMonthAdvance_bs_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_nonglexpense_ContractFK_bs_contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_nonglexpense_ContractFK_bs_contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_NonGLExpense> bs_nonglexpense_ContractFK_bs_contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_NonGLExpense>("bs_nonglexpense_ContractFK_bs_contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_NonGLExpense>("bs_nonglexpense_ContractFK_bs_contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_RevenueShareThreshold_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_RevenueShareThreshold_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_RevenueShareThreshold> bs_RevenueShareThreshold_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_RevenueShareThreshold>("bs_RevenueShareThreshold_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_RevenueShareThreshold>("bs_RevenueShareThreshold_Contract", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_StatementGenerationProcess_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_StatementGenerationProcess_Contract")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_StatementGenerationProcess> bs_StatementGenerationProcess_Contract
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_StatementGenerationProcess>("bs_StatementGenerationProcess_Contract", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_StatementGenerationProcess>("bs_StatementGenerationProcess_Contract", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bs_Contract_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_Contract_CustomerSite")]
		public TownePark.bs_CustomerSite bs_Contract_CustomerSite
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_CustomerSite>("bs_Contract_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_CustomerSite>("bs_Contract_CustomerSite", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
