#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Customer Site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_customersite_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Customer Site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_customersite_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Stores customer sites information
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_customersite")]
	public partial class bs_CustomerSite : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_customersite entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_AccountManager = "bs_accountmanager";
			public const string bs_AccountManagerId = "bs_accountmanagerid";
			public const string bs_Address = "bs_address";
			public const string bs_AssistantAccountManager = "bs_assistantaccountmanager";
			public const string bs_AssistantDistrictManager = "bs_assistantdistrictmanager";
			public const string bs_BillingContactEmail = "bs_billingcontactemail";
			public const string bs_BusinessSegment = "bs_businesssegment";
			public const string bs_CloseDate = "bs_closedate";
			public const string bs_COGSegment = "bs_cogsegment";
			public const string bs_CustomerSiteId = "bs_customersiteid";
			public const string Id = "bs_customersiteid";
			public const string bs_District = "bs_district";
			public const string bs_DistrictManager = "bs_districtmanager";
			public const string bs_GLString = "bs_glstring";
			public const string bs_InvoiceRecipient = "bs_invoicerecipient";
			public const string bs_LegalEntity = "bs_legalentity";
			public const string bs_PLCategory = "bs_plcategory";
			public const string bs_SiteName = "bs_sitename";
			public const string bs_SiteNumber = "bs_sitenumber";
			public const string bs_StartDate = "bs_startdate";
			public const string bs_SVPRegion = "bs_svpregion";
			public const string bs_TotalAvailableParking = "bs_totalavailableparking";
			public const string bs_TotalRoomsAvailable = "bs_totalroomsavailable";
			public const string bs_VendorId = "bs_vendorid";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_BillingStatement_CustomerSite = "bs_BillingStatement_CustomerSite";
			public const string bs_Contract_CustomerSite = "bs_Contract_CustomerSite";
			public const string bs_CustomerSite_cr9e8_readyforinvoice = "bs_CustomerSite_cr9e8_readyforinvoice";
			public const string bs_CustomerSite_CustomerSitesByUser = "bs_CustomerSite_CustomerSitesByUser";
			public const string bs_CustomerSite_JobCodesBySite = "bs_CustomerSite_JobCodesBySite";
			public const string bs_ForecastJobProfileMapping_CustomerSite = "bs_ForecastJobProfileMapping_CustomerSite";
			public const string bs_OtherExpenseDetail_CustomerSite = "bs_OtherExpenseDetail_CustomerSite";
			public const string bs_OtherRevenue_CustomerSite = "bs_OtherRevenue_CustomerSite";
			public const string bs_OtherRevenueDetail_CustomerSite = "bs_OtherRevenueDetail_CustomerSite";
			public const string bs_parkingrate_CustomerSiteFK_bs_customersite = "bs_parkingrate_CustomerSiteFK_bs_customersite";
			public const string bs_Payroll_CustomerSite = "bs_Payroll_CustomerSite";
			public const string bs_SiteStatistic_CustomerSite = "bs_SiteStatistic_CustomerSite";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_CustomerSite() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_customersite";
		
		public const string EntityLogicalCollectionName = "bs_customersites";
		
		public const string EntitySetName = "bs_customersites";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_accountmanager")]
		public string bs_AccountManager
		{
			get
			{
				return this.GetAttributeValue<string>("bs_accountmanager");
			}
			set
			{
				this.SetAttributeValue("bs_accountmanager", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_accountmanagerid")]
		public string bs_AccountManagerId
		{
			get
			{
				return this.GetAttributeValue<string>("bs_accountmanagerid");
			}
			set
			{
				this.SetAttributeValue("bs_accountmanagerid", value);
			}
		}
		
		/// <summary>
		/// Customer Site Address
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_address")]
		public string bs_Address
		{
			get
			{
				return this.GetAttributeValue<string>("bs_address");
			}
			set
			{
				this.SetAttributeValue("bs_address", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_assistantaccountmanager")]
		public string bs_AssistantAccountManager
		{
			get
			{
				return this.GetAttributeValue<string>("bs_assistantaccountmanager");
			}
			set
			{
				this.SetAttributeValue("bs_assistantaccountmanager", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_assistantdistrictmanager")]
		public string bs_AssistantDistrictManager
		{
			get
			{
				return this.GetAttributeValue<string>("bs_assistantdistrictmanager");
			}
			set
			{
				this.SetAttributeValue("bs_assistantdistrictmanager", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingcontactemail")]
		public string bs_BillingContactEmail
		{
			get
			{
				return this.GetAttributeValue<string>("bs_billingcontactemail");
			}
			set
			{
				this.SetAttributeValue("bs_billingcontactemail", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_businesssegment")]
		public string bs_BusinessSegment
		{
			get
			{
				return this.GetAttributeValue<string>("bs_businesssegment");
			}
			set
			{
				this.SetAttributeValue("bs_businesssegment", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_closedate")]
		public System.Nullable<System.DateTime> bs_CloseDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_closedate");
			}
			set
			{
				this.SetAttributeValue("bs_closedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_cogsegment")]
		public string bs_COGSegment
		{
			get
			{
				return this.GetAttributeValue<string>("bs_cogsegment");
			}
			set
			{
				this.SetAttributeValue("bs_cogsegment", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersiteid")]
		public System.Nullable<System.Guid> bs_CustomerSiteId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_customersiteid");
			}
			set
			{
				this.SetAttributeValue("bs_customersiteid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersiteid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_CustomerSiteId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_district")]
		public string bs_District
		{
			get
			{
				return this.GetAttributeValue<string>("bs_district");
			}
			set
			{
				this.SetAttributeValue("bs_district", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_districtmanager")]
		public string bs_DistrictManager
		{
			get
			{
				return this.GetAttributeValue<string>("bs_districtmanager");
			}
			set
			{
				this.SetAttributeValue("bs_districtmanager", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_glstring")]
		public string bs_GLString
		{
			get
			{
				return this.GetAttributeValue<string>("bs_glstring");
			}
			set
			{
				this.SetAttributeValue("bs_glstring", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_invoicerecipient")]
		public string bs_InvoiceRecipient
		{
			get
			{
				return this.GetAttributeValue<string>("bs_invoicerecipient");
			}
			set
			{
				this.SetAttributeValue("bs_invoicerecipient", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_legalentity")]
		public string bs_LegalEntity
		{
			get
			{
				return this.GetAttributeValue<string>("bs_legalentity");
			}
			set
			{
				this.SetAttributeValue("bs_legalentity", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_plcategory")]
		public string bs_PLCategory
		{
			get
			{
				return this.GetAttributeValue<string>("bs_plcategory");
			}
			set
			{
				this.SetAttributeValue("bs_plcategory", value);
			}
		}
		
		/// <summary>
		/// Name for the Customer Site
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitename")]
		public string bs_SiteName
		{
			get
			{
				return this.GetAttributeValue<string>("bs_sitename");
			}
			set
			{
				this.SetAttributeValue("bs_sitename", value);
			}
		}
		
		/// <summary>
		/// Unique code for site
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitenumber")]
		public string bs_SiteNumber
		{
			get
			{
				return this.GetAttributeValue<string>("bs_sitenumber");
			}
			set
			{
				this.SetAttributeValue("bs_sitenumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_startdate")]
		public System.Nullable<System.DateTime> bs_StartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_startdate");
			}
			set
			{
				this.SetAttributeValue("bs_startdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_svpregion")]
		public string bs_SVPRegion
		{
			get
			{
				return this.GetAttributeValue<string>("bs_svpregion");
			}
			set
			{
				this.SetAttributeValue("bs_svpregion", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_totalavailableparking")]
		public string bs_TotalAvailableParking
		{
			get
			{
				return this.GetAttributeValue<string>("bs_totalavailableparking");
			}
			set
			{
				this.SetAttributeValue("bs_totalavailableparking", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_totalroomsavailable")]
		public string bs_TotalRoomsAvailable
		{
			get
			{
				return this.GetAttributeValue<string>("bs_totalroomsavailable");
			}
			set
			{
				this.SetAttributeValue("bs_totalroomsavailable", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_vendorid")]
		public string bs_VendorId
		{
			get
			{
				return this.GetAttributeValue<string>("bs_vendorid");
			}
			set
			{
				this.SetAttributeValue("bs_vendorid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Customer Site
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_customersite_statecode? statecode
		{
			get
			{
				return ((bs_customersite_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Customer Site
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_customersite_statuscode? statuscode
		{
			get
			{
				return ((bs_customersite_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bs_BillingStatement_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_BillingStatement_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_BillingStatement> bs_BillingStatement_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_BillingStatement>("bs_BillingStatement_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_BillingStatement>("bs_BillingStatement_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_Contract_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_Contract_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_Contract> bs_Contract_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_Contract>("bs_Contract_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_Contract>("bs_Contract_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_CustomerSite_cr9e8_readyforinvoice
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_CustomerSite_cr9e8_readyforinvoice")]
		public System.Collections.Generic.IEnumerable<TownePark.cr9e8_readyforinvoice> bs_CustomerSite_cr9e8_readyforinvoice
		{
			get
			{
				return this.GetRelatedEntities<TownePark.cr9e8_readyforinvoice>("bs_CustomerSite_cr9e8_readyforinvoice", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.cr9e8_readyforinvoice>("bs_CustomerSite_cr9e8_readyforinvoice", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_CustomerSite_CustomerSitesByUser
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_CustomerSite_CustomerSitesByUser")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_CustomerSitesByUser> bs_CustomerSite_CustomerSitesByUser
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_CustomerSitesByUser>("bs_CustomerSite_CustomerSitesByUser", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_CustomerSitesByUser>("bs_CustomerSite_CustomerSitesByUser", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_CustomerSite_JobCodesBySite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_CustomerSite_JobCodesBySite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_JobCodesBySite> bs_CustomerSite_JobCodesBySite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_JobCodesBySite>("bs_CustomerSite_JobCodesBySite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_JobCodesBySite>("bs_CustomerSite_JobCodesBySite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_ForecastJobProfileMapping_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_ForecastJobProfileMapping_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_ForecastJobProfileMapping> bs_ForecastJobProfileMapping_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_ForecastJobProfileMapping>("bs_ForecastJobProfileMapping_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_ForecastJobProfileMapping>("bs_ForecastJobProfileMapping_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_OtherExpenseDetail_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_OtherExpenseDetail_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_OtherExpenseDetail> bs_OtherExpenseDetail_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_OtherExpenseDetail>("bs_OtherExpenseDetail_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_OtherExpenseDetail>("bs_OtherExpenseDetail_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_OtherRevenue_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_OtherRevenue_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_OtherRevenue> bs_OtherRevenue_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_OtherRevenue>("bs_OtherRevenue_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_OtherRevenue>("bs_OtherRevenue_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_OtherRevenueDetail_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_OtherRevenueDetail_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_OtherRevenueDetail> bs_OtherRevenueDetail_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_OtherRevenueDetail>("bs_OtherRevenueDetail_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_OtherRevenueDetail>("bs_OtherRevenueDetail_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_parkingrate_CustomerSiteFK_bs_customersite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_parkingrate_CustomerSiteFK_bs_customersite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_ParkingRate> bs_parkingrate_CustomerSiteFK_bs_customersite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_ParkingRate>("bs_parkingrate_CustomerSiteFK_bs_customersite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_ParkingRate>("bs_parkingrate_CustomerSiteFK_bs_customersite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_Payroll_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_Payroll_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_Payroll> bs_Payroll_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_Payroll>("bs_Payroll_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_Payroll>("bs_Payroll_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bs_SiteStatistic_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_SiteStatistic_CustomerSite")]
		public System.Collections.Generic.IEnumerable<TownePark.bs_SiteStatistic> bs_SiteStatistic_CustomerSite
		{
			get
			{
				return this.GetRelatedEntities<TownePark.bs_SiteStatistic>("bs_SiteStatistic_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntities<TownePark.bs_SiteStatistic>("bs_SiteStatistic_CustomerSite", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
