#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the LaborHourJob
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_laborhourjob_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the LaborHourJob
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_laborhourjob_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_laborhourjob")]
	public partial class bs_LaborHourJob : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_laborhourjob entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_Code = "bs_code";
			public const string bs_ContractFK = "bs_contractfk";
			public const string bs_DisplayName = "bs_displayname";
			public const string bs_EndDate = "bs_enddate";
			public const string bs_InvoiceGroup = "bs_invoicegroup";
			public const string bs_IsSalaried = "bs_issalaried";
			public const string bs_JobCode = "bs_jobcode";
			public const string bs_LaborHourJobId = "bs_laborhourjobid";
			public const string Id = "bs_laborhourjobid";
			public const string bs_Name = "bs_name";
			public const string bs_OvertimeRate = "bs_overtimerate";
			public const string bs_Rate = "bs_rate";
			public const string bs_StartDate = "bs_startdate";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_LaborHourJob_Contract = "bs_LaborHourJob_Contract";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_LaborHourJob() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_laborhourjob";
		
		public const string EntityLogicalCollectionName = "bs_laborhourjobs";
		
		public const string EntitySetName = "bs_laborhourjobs";
		
		/// <summary>
		/// Great Plains code for the Job
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_code")]
		public string bs_Code
		{
			get
			{
				return this.GetAttributeValue<string>("bs_code");
			}
			set
			{
				this.SetAttributeValue("bs_code", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_ContractFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_contractfk");
			}
			set
			{
				this.SetAttributeValue("bs_contractfk", value);
			}
		}
		
		/// <summary>
		/// Name of the Job displayed on invoices
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_displayname")]
		public string bs_DisplayName
		{
			get
			{
				return this.GetAttributeValue<string>("bs_displayname");
			}
			set
			{
				this.SetAttributeValue("bs_displayname", value);
			}
		}
		
		/// <summary>
		/// the end date for the effective time period
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_enddate")]
		public System.Nullable<System.DateTime> bs_EndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_enddate");
			}
			set
			{
				this.SetAttributeValue("bs_enddate", value);
			}
		}
		
		/// <summary>
		/// Which invoice group the line item belongs to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_invoicegroup")]
		public System.Nullable<int> bs_InvoiceGroup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_invoicegroup");
			}
			set
			{
				this.SetAttributeValue("bs_invoicegroup", value);
			}
		}
		
		/// <summary>
		/// Job Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_issalaried")]
		public System.Nullable<bool> bs_IsSalaried
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_issalaried");
			}
			set
			{
				this.SetAttributeValue("bs_issalaried", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_jobcode")]
		public string bs_JobCode
		{
			get
			{
				return this.GetAttributeValue<string>("bs_jobcode");
			}
			set
			{
				this.SetAttributeValue("bs_jobcode", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_laborhourjobid")]
		public System.Nullable<System.Guid> bs_LaborHourJobId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_laborhourjobid");
			}
			set
			{
				this.SetAttributeValue("bs_laborhourjobid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_laborhourjobid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_LaborHourJobId = value;
			}
		}
		
		/// <summary>
		/// Name of the Job
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		/// <summary>
		/// Overtime rate for the Job
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_overtimerate")]
		public System.Nullable<decimal> bs_OvertimeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_overtimerate");
			}
			set
			{
				this.SetAttributeValue("bs_overtimerate", value);
			}
		}
		
		/// <summary>
		/// Standard rate for the Job
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_rate")]
		public System.Nullable<decimal> bs_Rate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_rate");
			}
			set
			{
				this.SetAttributeValue("bs_rate", value);
			}
		}
		
		/// <summary>
		/// the start date of the effective time period
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_startdate")]
		public System.Nullable<System.DateTime> bs_StartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_startdate");
			}
			set
			{
				this.SetAttributeValue("bs_startdate", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the LaborHourJob
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_laborhourjob_statecode? statecode
		{
			get
			{
				return ((bs_laborhourjob_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the LaborHourJob
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_laborhourjob_statuscode? statuscode
		{
			get
			{
				return ((bs_laborhourjob_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_LaborHourJob_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_LaborHourJob_Contract")]
		public TownePark.bs_Contract bs_LaborHourJob_Contract
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_Contract>("bs_LaborHourJob_Contract", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_Contract>("bs_LaborHourJob_Contract", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
