#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Master Customer Site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_mastercustomersite_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Master Customer Site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_mastercustomersite_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_mastercustomersite")]
	public partial class bs_MasterCustomerSite : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_mastercustomersite entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_AccountManager = "bs_accountmanager";
			public const string bs_AccountManagerId = "bs_accountmanagerid";
			public const string bs_Address = "bs_address";
			public const string bs_BillingContactEmail = "bs_billingcontactemail";
			public const string bs_BusinessSegment = "bs_businesssegment";
			public const string bs_COGSegment = "bs_cogsegment";
			public const string bs_ContractTypeString = "bs_contracttypestring";
			public const string bs_Deposits = "bs_deposits";
			public const string bs_District = "bs_district";
			public const string bs_GLString = "bs_glstring";
			public const string bs_LegalEntity = "bs_legalentity";
			public const string bs_MasterCustomerSiteId = "bs_mastercustomersiteid";
			public const string Id = "bs_mastercustomersiteid";
			public const string bs_PLCategory = "bs_plcategory";
			public const string bs_SiteName = "bs_sitename";
			public const string bs_SiteNumber = "bs_sitenumber";
			public const string bs_StartDate = "bs_startdate";
			public const string bs_SVPRegion = "bs_svpregion";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_MasterCustomerSite() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_mastercustomersite";
		
		public const string EntityLogicalCollectionName = "bs_mastercustomersites";
		
		public const string EntitySetName = "bs_mastercustomersites";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_accountmanager")]
		public string bs_AccountManager
		{
			get
			{
				return this.GetAttributeValue<string>("bs_accountmanager");
			}
			set
			{
				this.SetAttributeValue("bs_accountmanager", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_accountmanagerid")]
		public string bs_AccountManagerId
		{
			get
			{
				return this.GetAttributeValue<string>("bs_accountmanagerid");
			}
			set
			{
				this.SetAttributeValue("bs_accountmanagerid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_address")]
		public string bs_Address
		{
			get
			{
				return this.GetAttributeValue<string>("bs_address");
			}
			set
			{
				this.SetAttributeValue("bs_address", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingcontactemail")]
		public string bs_BillingContactEmail
		{
			get
			{
				return this.GetAttributeValue<string>("bs_billingcontactemail");
			}
			set
			{
				this.SetAttributeValue("bs_billingcontactemail", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_businesssegment")]
		public string bs_BusinessSegment
		{
			get
			{
				return this.GetAttributeValue<string>("bs_businesssegment");
			}
			set
			{
				this.SetAttributeValue("bs_businesssegment", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_cogsegment")]
		public string bs_COGSegment
		{
			get
			{
				return this.GetAttributeValue<string>("bs_cogsegment");
			}
			set
			{
				this.SetAttributeValue("bs_cogsegment", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contracttypestring")]
		public string bs_ContractTypeString
		{
			get
			{
				return this.GetAttributeValue<string>("bs_contracttypestring");
			}
			set
			{
				this.SetAttributeValue("bs_contracttypestring", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_deposits")]
		public System.Nullable<bool> bs_Deposits
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_deposits");
			}
			set
			{
				this.SetAttributeValue("bs_deposits", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_district")]
		public string bs_District
		{
			get
			{
				return this.GetAttributeValue<string>("bs_district");
			}
			set
			{
				this.SetAttributeValue("bs_district", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_glstring")]
		public string bs_GLString
		{
			get
			{
				return this.GetAttributeValue<string>("bs_glstring");
			}
			set
			{
				this.SetAttributeValue("bs_glstring", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_legalentity")]
		public string bs_LegalEntity
		{
			get
			{
				return this.GetAttributeValue<string>("bs_legalentity");
			}
			set
			{
				this.SetAttributeValue("bs_legalentity", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_mastercustomersiteid")]
		public System.Nullable<System.Guid> bs_MasterCustomerSiteId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_mastercustomersiteid");
			}
			set
			{
				this.SetAttributeValue("bs_mastercustomersiteid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_mastercustomersiteid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_MasterCustomerSiteId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_plcategory")]
		public string bs_PLCategory
		{
			get
			{
				return this.GetAttributeValue<string>("bs_plcategory");
			}
			set
			{
				this.SetAttributeValue("bs_plcategory", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitename")]
		public string bs_SiteName
		{
			get
			{
				return this.GetAttributeValue<string>("bs_sitename");
			}
			set
			{
				this.SetAttributeValue("bs_sitename", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitenumber")]
		public string bs_SiteNumber
		{
			get
			{
				return this.GetAttributeValue<string>("bs_sitenumber");
			}
			set
			{
				this.SetAttributeValue("bs_sitenumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_startdate")]
		public System.Nullable<System.DateTime> bs_StartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_startdate");
			}
			set
			{
				this.SetAttributeValue("bs_startdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_svpregion")]
		public string bs_SVPRegion
		{
			get
			{
				return this.GetAttributeValue<string>("bs_svpregion");
			}
			set
			{
				this.SetAttributeValue("bs_svpregion", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Master Customer Site
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_mastercustomersite_statecode? statecode
		{
			get
			{
				return ((bs_mastercustomersite_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Master Customer Site
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_mastercustomersite_statuscode? statuscode
		{
			get
			{
				return ((bs_mastercustomersite_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
}
#pragma warning restore CS1591
