#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Management Agreement
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_managementagreement_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Management Agreement
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_managementagreement_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_managementagreement")]
	public partial class bs_ManagementAgreement : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_managementagreement entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_ClaimsCapAmount = "bs_claimscapamount";
			public const string bs_ClaimsEnabled = "bs_claimsenabled";
			public const string bs_ClaimsLineTitle = "bs_claimslinetitle";
			public const string bs_ClaimsType = "bs_claimstype";
			public const string bs_ContractFK = "bs_contractfk";
			public const string bs_FixedFeeAmount = "bs_fixedfeeamount";
			public const string bs_InsuranceAdditionalPercentage = "bs_insuranceadditionalpercentage";
			public const string bs_InsuranceEnabled = "bs_insuranceenabled";
			public const string bs_InsuranceFixedFeeAmount = "bs_insurancefixedfeeamount";
			public const string bs_InsuranceLineTitle = "bs_insurancelinetitle";
			public const string bs_InsuranceType = "bs_insurancetype";
			public const string bs_InvoiceGroup = "bs_invoicegroup";
			public const string bs_ManagementAgreementId = "bs_managementagreementid";
			public const string Id = "bs_managementagreementid";
			public const string bs_ManagementAgreementType = "bs_managementagreementtype";
			public const string bs_ManagementFeeEscalatorEnabled = "bs_managementfeeescalatorenabled";
			public const string bs_ManagementFeeEscalatorMonth = "bs_managementfeeescalatormonth";
			public const string bs_ManagementFeeEscalatorType = "bs_managementfeeescalatortype";
			public const string bs_ManagementFeeEscalatorValue = "bs_managementfeeescalatorvalue";
			public const string bs_Name = "bs_name";
			public const string bs_NonGLBillableExpensesEnabled = "bs_nonglbillableexpensesenabled";
			public const string bs_PerLaborHourJobCode = "bs_perlaborhourjobcode";
			public const string bs_PerLaborHourJobCodeData = "bs_perlaborhourjobcodedata";
			public const string bs_PerLaborHourOvertimeRate = "bs_perlaborhourovertimerate";
			public const string bs_PerLaborHourRate = "bs_perlaborhourrate";
			public const string bs_ProfitShareAccumulationType = "bs_profitshareaccumulationtype";
			public const string bs_ProfitShareEnabled = "bs_profitshareenabled";
			public const string bs_ProfitShareEscalatorEnabled = "bs_profitshareescalatorenabled";
			public const string bs_ProfitShareEscalatorMonth = "bs_profitshareescalatormonth";
			public const string bs_ProfitShareEscalatorType = "bs_profitshareescalatortype";
			public const string bs_ProfitShareTierData = "bs_profitsharetierdata";
			public const string bs_RevenuePercentageAmount = "bs_revenuepercentageamount";
			public const string bs_ValidationThresholdAmount = "bs_validationthresholdamount";
			public const string bs_ValidationThresholdEnabled = "bs_validationthresholdenabled";
			public const string bs_ValidationThresholdType = "bs_validationthresholdtype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_ManagementAgreement_Contract = "bs_ManagementAgreement_Contract";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_ManagementAgreement() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_managementagreement";
		
		public const string EntityLogicalCollectionName = "bs_managementagreements";
		
		public const string EntitySetName = "bs_managementagreements";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_claimscapamount")]
		public System.Nullable<decimal> bs_ClaimsCapAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_claimscapamount");
			}
			set
			{
				this.SetAttributeValue("bs_claimscapamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_claimsenabled")]
		public System.Nullable<bool> bs_ClaimsEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_claimsenabled");
			}
			set
			{
				this.SetAttributeValue("bs_claimsenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_claimslinetitle")]
		public string bs_ClaimsLineTitle
		{
			get
			{
				return this.GetAttributeValue<string>("bs_claimslinetitle");
			}
			set
			{
				this.SetAttributeValue("bs_claimslinetitle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_claimstype")]
		public virtual bs_claimtype? bs_ClaimsType
		{
			get
			{
				return ((bs_claimtype?)(EntityOptionSetEnum.GetEnum(this, "bs_claimstype")));
			}
			set
			{
				this.SetAttributeValue("bs_claimstype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_ContractFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_contractfk");
			}
			set
			{
				this.SetAttributeValue("bs_contractfk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_fixedfeeamount")]
		public System.Nullable<decimal> bs_FixedFeeAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_fixedfeeamount");
			}
			set
			{
				this.SetAttributeValue("bs_fixedfeeamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_insuranceadditionalpercentage")]
		public System.Nullable<decimal> bs_InsuranceAdditionalPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_insuranceadditionalpercentage");
			}
			set
			{
				this.SetAttributeValue("bs_insuranceadditionalpercentage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_insuranceenabled")]
		public System.Nullable<bool> bs_InsuranceEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_insuranceenabled");
			}
			set
			{
				this.SetAttributeValue("bs_insuranceenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_insurancefixedfeeamount")]
		public System.Nullable<decimal> bs_InsuranceFixedFeeAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_insurancefixedfeeamount");
			}
			set
			{
				this.SetAttributeValue("bs_insurancefixedfeeamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_insurancelinetitle")]
		public string bs_InsuranceLineTitle
		{
			get
			{
				return this.GetAttributeValue<string>("bs_insurancelinetitle");
			}
			set
			{
				this.SetAttributeValue("bs_insurancelinetitle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_insurancetype")]
		public virtual bs_managementagreementinsurancetype? bs_InsuranceType
		{
			get
			{
				return ((bs_managementagreementinsurancetype?)(EntityOptionSetEnum.GetEnum(this, "bs_insurancetype")));
			}
			set
			{
				this.SetAttributeValue("bs_insurancetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_invoicegroup")]
		public System.Nullable<int> bs_InvoiceGroup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_invoicegroup");
			}
			set
			{
				this.SetAttributeValue("bs_invoicegroup", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_managementagreementid")]
		public System.Nullable<System.Guid> bs_ManagementAgreementId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_managementagreementid");
			}
			set
			{
				this.SetAttributeValue("bs_managementagreementid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_managementagreementid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_ManagementAgreementId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_managementagreementtype")]
		public virtual bs_managementagreementtype? bs_ManagementAgreementType
		{
			get
			{
				return ((bs_managementagreementtype?)(EntityOptionSetEnum.GetEnum(this, "bs_managementagreementtype")));
			}
			set
			{
				this.SetAttributeValue("bs_managementagreementtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_managementfeeescalatorenabled")]
		public System.Nullable<bool> bs_ManagementFeeEscalatorEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_managementfeeescalatorenabled");
			}
			set
			{
				this.SetAttributeValue("bs_managementfeeescalatorenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_managementfeeescalatormonth")]
		public System.Nullable<int> bs_ManagementFeeEscalatorMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_managementfeeescalatormonth");
			}
			set
			{
				this.SetAttributeValue("bs_managementfeeescalatormonth", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_managementfeeescalatortype")]
		public virtual bs_escalatortype? bs_ManagementFeeEscalatorType
		{
			get
			{
				return ((bs_escalatortype?)(EntityOptionSetEnum.GetEnum(this, "bs_managementfeeescalatortype")));
			}
			set
			{
				this.SetAttributeValue("bs_managementfeeescalatortype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_managementfeeescalatorvalue")]
		public System.Nullable<decimal> bs_ManagementFeeEscalatorValue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_managementfeeescalatorvalue");
			}
			set
			{
				this.SetAttributeValue("bs_managementfeeescalatorvalue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		/// <summary>
		/// Non-GL Billable Expenses Enabled
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_nonglbillableexpensesenabled")]
		public System.Nullable<bool> bs_NonGLBillableExpensesEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_nonglbillableexpensesenabled");
			}
			set
			{
				this.SetAttributeValue("bs_nonglbillableexpensesenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_perlaborhourjobcode")]
		public string bs_PerLaborHourJobCode
		{
			get
			{
				return this.GetAttributeValue<string>("bs_perlaborhourjobcode");
			}
			set
			{
				this.SetAttributeValue("bs_perlaborhourjobcode", value);
			}
		}
		
		/// <summary>
		/// Per Labor Hour Job Code Data
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_perlaborhourjobcodedata")]
		public string bs_PerLaborHourJobCodeData
		{
			get
			{
				return this.GetAttributeValue<string>("bs_perlaborhourjobcodedata");
			}
			set
			{
				this.SetAttributeValue("bs_perlaborhourjobcodedata", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_perlaborhourovertimerate")]
		public System.Nullable<decimal> bs_PerLaborHourOvertimeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_perlaborhourovertimerate");
			}
			set
			{
				this.SetAttributeValue("bs_perlaborhourovertimerate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_perlaborhourrate")]
		public System.Nullable<decimal> bs_PerLaborHourRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_perlaborhourrate");
			}
			set
			{
				this.SetAttributeValue("bs_perlaborhourrate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitshareaccumulationtype")]
		public virtual bs_profitshareaccumulationtype? bs_ProfitShareAccumulationType
		{
			get
			{
				return ((bs_profitshareaccumulationtype?)(EntityOptionSetEnum.GetEnum(this, "bs_profitshareaccumulationtype")));
			}
			set
			{
				this.SetAttributeValue("bs_profitshareaccumulationtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitshareenabled")]
		public System.Nullable<bool> bs_ProfitShareEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_profitshareenabled");
			}
			set
			{
				this.SetAttributeValue("bs_profitshareenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitshareescalatorenabled")]
		public System.Nullable<bool> bs_ProfitShareEscalatorEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_profitshareescalatorenabled");
			}
			set
			{
				this.SetAttributeValue("bs_profitshareescalatorenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitshareescalatormonth")]
		public System.Nullable<int> bs_ProfitShareEscalatorMonth
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_profitshareescalatormonth");
			}
			set
			{
				this.SetAttributeValue("bs_profitshareescalatormonth", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitshareescalatortype")]
		public virtual bs_escalatortype? bs_ProfitShareEscalatorType
		{
			get
			{
				return ((bs_escalatortype?)(EntityOptionSetEnum.GetEnum(this, "bs_profitshareescalatortype")));
			}
			set
			{
				this.SetAttributeValue("bs_profitshareescalatortype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitsharetierdata")]
		public string bs_ProfitShareTierData
		{
			get
			{
				return this.GetAttributeValue<string>("bs_profitsharetierdata");
			}
			set
			{
				this.SetAttributeValue("bs_profitsharetierdata", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_revenuepercentageamount")]
		public System.Nullable<decimal> bs_RevenuePercentageAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_revenuepercentageamount");
			}
			set
			{
				this.SetAttributeValue("bs_revenuepercentageamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_validationthresholdamount")]
		public System.Nullable<decimal> bs_ValidationThresholdAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_validationthresholdamount");
			}
			set
			{
				this.SetAttributeValue("bs_validationthresholdamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_validationthresholdenabled")]
		public System.Nullable<bool> bs_ValidationThresholdEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bs_validationthresholdenabled");
			}
			set
			{
				this.SetAttributeValue("bs_validationthresholdenabled", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_validationthresholdtype")]
		public virtual bs_managementagreementvalidationtype? bs_ValidationThresholdType
		{
			get
			{
				return ((bs_managementagreementvalidationtype?)(EntityOptionSetEnum.GetEnum(this, "bs_validationthresholdtype")));
			}
			set
			{
				this.SetAttributeValue("bs_validationthresholdtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Management Agreement
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_managementagreement_statecode? statecode
		{
			get
			{
				return ((bs_managementagreement_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Management Agreement
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_managementagreement_statuscode? statuscode
		{
			get
			{
				return ((bs_managementagreement_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_ManagementAgreement_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_ManagementAgreement_Contract")]
		public TownePark.bs_Contract bs_ManagementAgreement_Contract
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_Contract>("bs_ManagementAgreement_Contract", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_Contract>("bs_ManagementAgreement_Contract", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
