#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{


    /// <summary>
    /// Status of the Non GL Expense
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum bs_nonglexpense_statecode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
    }

    /// <summary>
    /// Reason for the status of the Non GL Expense
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum bs_nonglexpense_statuscode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }

    /// <summary>
    /// Non GL Expense
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_nonglexpense")]
    public partial class bs_NonGLExpense : Microsoft.Xrm.Sdk.Entity
    {

        /// <summary>
        /// Available fields, a the time of codegen, for the bs_nonglexpense entity
        /// </summary>
        public partial class Fields
        {
            public const string bs_ContractFK = "bs_contractfk";
            public const string bs_ExpenseAmount = "bs_expenseamount";
            public const string bs_ExpensePayrollType = "bs_expensepayrolltype";
            public const string bs_ExpenseTitle = "bs_expensetitle";
            public const string bs_FinalPeriodBilled = "bs_finalperiodbilled";
            public const string bs_Name = "bs_name";
            public const string bs_NonGLExpenseId = "bs_nonglexpenseid";
            public const string Id = "bs_nonglexpenseid";
            public const string bs_NonGLExpenseType = "bs_nonglexpensetype";
            public const string bs_SequenceNumber = "bs_sequencenumber";
            public const string CreatedBy = "createdby";
            public const string CreatedOn = "createdon";
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            public const string ImportSequenceNumber = "importsequencenumber";
            public const string ModifiedBy = "modifiedby";
            public const string ModifiedOn = "modifiedon";
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            public const string OverriddenCreatedOn = "overriddencreatedon";
            public const string OwnerId = "ownerid";
            public const string OwningBusinessUnit = "owningbusinessunit";
            public const string OwningTeam = "owningteam";
            public const string OwningUser = "owninguser";
            public const string statecode = "statecode";
            public const string statuscode = "statuscode";
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
            public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
            public const string VersionNumber = "versionnumber";
            public const string bs_nonglexpense_ContractFK_bs_contract = "bs_nonglexpense_ContractFK_bs_contract";
        }

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public bs_NonGLExpense() :
                base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "bs_nonglexpense";

        public const string EntityLogicalCollectionName = "bs_nonglexpenses";

        public const string EntitySetName = "bs_nonglexpenses";

        /// <summary>
        /// Contract FK
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
        public Microsoft.Xrm.Sdk.EntityReference bs_ContractFK
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_contractfk");
            }
            set
            {
                this.SetAttributeValue("bs_contractfk", value);
            }
        }

        /// <summary>
        /// Expense Amount
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_expenseamount")]
        public System.Nullable<decimal> bs_ExpenseAmount
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("bs_expenseamount");
            }
            set
            {
                this.SetAttributeValue("bs_expenseamount", value);
            }
        }

        /// <summary>
        /// Expense Payroll Type
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_expensepayrolltype")]
        public virtual bs_nonglpayrolltype? bs_ExpensePayrollType
        {
            get
            {
                return ((bs_nonglpayrolltype?)(EntityOptionSetEnum.GetEnum(this, "bs_expensepayrolltype")));
            }
            set
            {
                this.SetAttributeValue("bs_expensepayrolltype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        /// <summary>
        /// Expense Title
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_expensetitle")]
        public string bs_ExpenseTitle
        {
            get
            {
                return this.GetAttributeValue<string>("bs_expensetitle");
            }
            set
            {
                this.SetAttributeValue("bs_expensetitle", value);
            }
        }

        /// <summary>
        /// Final Period Billed
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_finalperiodbilled")]
        public System.Nullable<System.DateTime> bs_FinalPeriodBilled
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_finalperiodbilled");
            }
            set
            {
                this.SetAttributeValue("bs_finalperiodbilled", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
        public string bs_Name
        {
            get
            {
                return this.GetAttributeValue<string>("bs_name");
            }
            set
            {
                this.SetAttributeValue("bs_name", value);
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_nonglexpenseid")]
        public System.Nullable<System.Guid> bs_NonGLExpenseId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_nonglexpenseid");
            }
            set
            {
                this.SetAttributeValue("bs_nonglexpenseid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_nonglexpenseid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.bs_NonGLExpenseId = value;
            }
        }

        /// <summary>
        /// Non GL Expense Type
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_nonglexpensetype")]
        public virtual bs_nonglexpensetype? bs_NonGLExpenseType
        {
            get
            {
                return ((bs_nonglexpensetype?)(EntityOptionSetEnum.GetEnum(this, "bs_nonglexpensetype")));
            }
            set
            {
                this.SetAttributeValue("bs_nonglexpensetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        /// <summary>
        /// Sequence Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sequencenumber")]
        public System.Nullable<int> bs_SequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("bs_sequencenumber");
            }
            set
            {
                this.SetAttributeValue("bs_sequencenumber", value);
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Non GL Expense
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public virtual bs_nonglexpense_statecode? statecode
        {
            get
            {
                return ((bs_nonglexpense_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
            }
            set
            {
                this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        /// <summary>
        /// Reason for the status of the Non GL Expense
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public virtual bs_nonglexpense_statuscode? statuscode
        {
            get
            {
                return ((bs_nonglexpense_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
            }
            set
            {
                this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// N:1 bs_nonglexpense_ContractFK_bs_contract
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contractfk")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_nonglexpense_ContractFK_bs_contract")]
        public TownePark.bs_Contract bs_nonglexpense_ContractFK_bs_contract
        {
            get
            {
                return this.GetRelatedEntity<TownePark.bs_Contract>("bs_nonglexpense_ContractFK_bs_contract", null);
            }
            set
            {
                this.SetRelatedEntity<TownePark.bs_Contract>("bs_nonglexpense_ContractFK_bs_contract", null, value);
            }
        }
    }
}
#pragma warning restore CS1591
