#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Other Revenue Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_otherrevenuedetail_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Other Revenue Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_otherrevenuedetail_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_otherrevenuedetail")]
	public partial class bs_OtherRevenueDetail : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_otherrevenuedetail entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_BillableExpense = "bs_billableexpense";
			public const string bs_ClientPaidExpense = "bs_clientpaidexpense";
			public const string bs_Credits = "bs_credits";
			public const string bs_CustomerSiteFK = "bs_customersitefk";
			public const string bs_GPOFees = "bs_gpofees";
			public const string bs_Miscellaneous = "bs_miscellaneous";
			public const string bs_MonthYear = "bs_monthyear";
			public const string bs_Name = "bs_name";
			public const string bs_OtherRevenueDetailId = "bs_otherrevenuedetailid";
			public const string Id = "bs_otherrevenuedetailid";
			public const string bs_OtherRevenueFK = "bs_otherrevenuefk";
			public const string bs_RevenueValidation = "bs_revenuevalidation";
			public const string bs_SigningBonus = "bs_signingbonus";
			public const string bs_Type = "bs_type";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_OtherRevenueDetail_CustomerSite = "bs_OtherRevenueDetail_CustomerSite";
			public const string bs_OtherRevenueDetail_OtherRevenue = "bs_OtherRevenueDetail_OtherRevenue";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_OtherRevenueDetail() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_otherrevenuedetail";
		
		public const string EntityLogicalCollectionName = "bs_otherrevenuedetails";
		
		public const string EntitySetName = "bs_otherrevenuedetails";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billableexpense")]
		public System.Nullable<decimal> bs_BillableExpense
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_billableexpense");
			}
			set
			{
				this.SetAttributeValue("bs_billableexpense", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_clientpaidexpense")]
		public System.Nullable<decimal> bs_ClientPaidExpense
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_clientpaidexpense");
			}
			set
			{
				this.SetAttributeValue("bs_clientpaidexpense", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_credits")]
		public System.Nullable<decimal> bs_Credits
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_credits");
			}
			set
			{
				this.SetAttributeValue("bs_credits", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_CustomerSiteFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_customersitefk");
			}
			set
			{
				this.SetAttributeValue("bs_customersitefk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_gpofees")]
		public System.Nullable<decimal> bs_GPOFees
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_gpofees");
			}
			set
			{
				this.SetAttributeValue("bs_gpofees", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_miscellaneous")]
		public System.Nullable<decimal> bs_Miscellaneous
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_miscellaneous");
			}
			set
			{
				this.SetAttributeValue("bs_miscellaneous", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_monthyear")]
		public string bs_MonthYear
		{
			get
			{
				return this.GetAttributeValue<string>("bs_monthyear");
			}
			set
			{
				this.SetAttributeValue("bs_monthyear", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_otherrevenuedetailid")]
		public System.Nullable<System.Guid> bs_OtherRevenueDetailId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_otherrevenuedetailid");
			}
			set
			{
				this.SetAttributeValue("bs_otherrevenuedetailid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_otherrevenuedetailid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_OtherRevenueDetailId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_otherrevenuefk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_OtherRevenueFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_otherrevenuefk");
			}
			set
			{
				this.SetAttributeValue("bs_otherrevenuefk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_revenuevalidation")]
		public System.Nullable<decimal> bs_RevenueValidation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_revenuevalidation");
			}
			set
			{
				this.SetAttributeValue("bs_revenuevalidation", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_signingbonus")]
		public System.Nullable<decimal> bs_SigningBonus
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_signingbonus");
			}
			set
			{
				this.SetAttributeValue("bs_signingbonus", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_type")]
		public virtual bs_otherrevenuetypes? bs_Type
		{
			get
			{
				return ((bs_otherrevenuetypes?)(EntityOptionSetEnum.GetEnum(this, "bs_type")));
			}
			set
			{
				this.SetAttributeValue("bs_type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Other Revenue Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_otherrevenuedetail_statecode? statecode
		{
			get
			{
				return ((bs_otherrevenuedetail_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Other Revenue Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_otherrevenuedetail_statuscode? statuscode
		{
			get
			{
				return ((bs_otherrevenuedetail_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_OtherRevenueDetail_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_OtherRevenueDetail_CustomerSite")]
		public TownePark.bs_CustomerSite bs_OtherRevenueDetail_CustomerSite
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_CustomerSite>("bs_OtherRevenueDetail_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_CustomerSite>("bs_OtherRevenueDetail_CustomerSite", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bs_OtherRevenueDetail_OtherRevenue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_otherrevenuefk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_OtherRevenueDetail_OtherRevenue")]
		public TownePark.bs_OtherRevenue bs_OtherRevenueDetail_OtherRevenue
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_OtherRevenue>("bs_OtherRevenueDetail_OtherRevenue", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_OtherRevenue>("bs_OtherRevenueDetail_OtherRevenue", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
