#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Other Expense Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_otherexpensedetail_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Other Expense Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_otherexpensedetail_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_otherexpensedetail")]
	public partial class bs_OtherExpenseDetail : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_otherexpensedetail entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_CustomerSiteFK = "bs_customersitefk";
			public const string bs_EmployeeRelations = "bs_employeerelations";
			public const string bs_FuelVehicles = "bs_fuelvehicles";
			public const string bs_LossAndDamageClaims = "bs_lossanddamageclaims";
			public const string bs_MiscOtherExpenses = "bs_miscotherexpenses";
			public const string bs_MonthYear = "bs_monthyear";
			public const string bs_Name = "bs_name";
			public const string bs_OfficeSupplies = "bs_officesupplies";
			public const string bs_OtherExpenseDetailId = "bs_otherexpensedetailid";
			public const string Id = "bs_otherexpensedetailid";
			public const string bs_OutsideServices = "bs_outsideservices";
			public const string bs_RentsParking = "bs_rentsparking";
			public const string bs_RepairsAndMaintenance = "bs_repairsandmaintenance";
			public const string bs_RepairsAndMaintenanceVehicle = "bs_repairsandmaintenancevehicle";
			public const string bs_Signage = "bs_signage";
			public const string bs_SuppliesAndEquipment = "bs_suppliesandequipment";
			public const string bs_TicketsAndPrintedMaterial = "bs_ticketsandprintedmaterial";
			public const string bs_TotalOtherExpenses = "bs_totalotherexpenses";
			public const string bs_Uniforms = "bs_uniforms";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_OtherExpenseDetail_CustomerSite = "bs_OtherExpenseDetail_CustomerSite";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_OtherExpenseDetail() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_otherexpensedetail";
		
		public const string EntityLogicalCollectionName = "bs_otherexpensedetails";
		
		public const string EntitySetName = "bs_otherexpensedetails";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_CustomerSiteFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_customersitefk");
			}
			set
			{
				this.SetAttributeValue("bs_customersitefk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_employeerelations")]
		public System.Nullable<decimal> bs_EmployeeRelations
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_employeerelations");
			}
			set
			{
				this.SetAttributeValue("bs_employeerelations", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_fuelvehicles")]
		public System.Nullable<decimal> bs_FuelVehicles
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_fuelvehicles");
			}
			set
			{
				this.SetAttributeValue("bs_fuelvehicles", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_lossanddamageclaims")]
		public System.Nullable<decimal> bs_LossAndDamageClaims
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_lossanddamageclaims");
			}
			set
			{
				this.SetAttributeValue("bs_lossanddamageclaims", value);
			}
		}
		
		/// <summary>
		/// Sum of additional other expenses
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_miscotherexpenses")]
		public System.Nullable<decimal> bs_MiscOtherExpenses
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_miscotherexpenses");
			}
			set
			{
				this.SetAttributeValue("bs_miscotherexpenses", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_monthyear")]
		public string bs_MonthYear
		{
			get
			{
				return this.GetAttributeValue<string>("bs_monthyear");
			}
			set
			{
				this.SetAttributeValue("bs_monthyear", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_officesupplies")]
		public System.Nullable<decimal> bs_OfficeSupplies
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_officesupplies");
			}
			set
			{
				this.SetAttributeValue("bs_officesupplies", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_otherexpensedetailid")]
		public System.Nullable<System.Guid> bs_OtherExpenseDetailId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_otherexpensedetailid");
			}
			set
			{
				this.SetAttributeValue("bs_otherexpensedetailid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_otherexpensedetailid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_OtherExpenseDetailId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_outsideservices")]
		public System.Nullable<decimal> bs_OutsideServices
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_outsideservices");
			}
			set
			{
				this.SetAttributeValue("bs_outsideservices", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_rentsparking")]
		public System.Nullable<decimal> bs_RentsParking
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_rentsparking");
			}
			set
			{
				this.SetAttributeValue("bs_rentsparking", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_repairsandmaintenance")]
		public System.Nullable<decimal> bs_RepairsAndMaintenance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_repairsandmaintenance");
			}
			set
			{
				this.SetAttributeValue("bs_repairsandmaintenance", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_repairsandmaintenancevehicle")]
		public System.Nullable<decimal> bs_RepairsAndMaintenanceVehicle
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_repairsandmaintenancevehicle");
			}
			set
			{
				this.SetAttributeValue("bs_repairsandmaintenancevehicle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_signage")]
		public System.Nullable<decimal> bs_Signage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_signage");
			}
			set
			{
				this.SetAttributeValue("bs_signage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_suppliesandequipment")]
		public System.Nullable<decimal> bs_SuppliesAndEquipment
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_suppliesandequipment");
			}
			set
			{
				this.SetAttributeValue("bs_suppliesandequipment", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_ticketsandprintedmaterial")]
		public System.Nullable<decimal> bs_TicketsAndPrintedMaterial
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_ticketsandprintedmaterial");
			}
			set
			{
				this.SetAttributeValue("bs_ticketsandprintedmaterial", value);
			}
		}
		
		/// <summary>
		/// Sum of all expense accounts including the 12 input columns and Misc
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_totalotherexpenses")]
		public System.Nullable<decimal> bs_TotalOtherExpenses
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_totalotherexpenses");
			}
			set
			{
				this.SetAttributeValue("bs_totalotherexpenses", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_uniforms")]
		public System.Nullable<decimal> bs_Uniforms
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_uniforms");
			}
			set
			{
				this.SetAttributeValue("bs_uniforms", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Other Expense Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_otherexpensedetail_statecode? statecode
		{
			get
			{
				return ((bs_otherexpensedetail_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Other Expense Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_otherexpensedetail_statuscode? statuscode
		{
			get
			{
				return ((bs_otherexpensedetail_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_OtherExpenseDetail_CustomerSite
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_OtherExpenseDetail_CustomerSite")]
		public TownePark.bs_CustomerSite bs_OtherExpenseDetail_CustomerSite
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_CustomerSite>("bs_OtherExpenseDetail_CustomerSite", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_CustomerSite>("bs_OtherExpenseDetail_CustomerSite", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
