#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Profit Share By Percentage
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_profitsharebypercentage_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Profit Share By Percentage
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_profitsharebypercentage_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_profitsharebypercentage")]
	public partial class bs_ProfitShareByPercentage : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_profitsharebypercentage entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_BillingStatementFK = "bs_billingstatementfk";
			public const string bs_Month = "bs_month";
			public const string bs_Name = "bs_name";
			public const string bs_OwnerPercent = "bs_ownerpercent";
			public const string bs_OwnerPercentDisplay = "bs_ownerpercentdisplay";
			public const string bs_PercentToCharge = "bs_percenttocharge";
			public const string bs_ProfitAmount = "bs_profitamount";
			public const string bs_ProfitShareByPercentageId = "bs_profitsharebypercentageid";
			public const string Id = "bs_profitsharebypercentageid";
			public const string bs_Site = "bs_site";
			public const string bs_TierLimitAmount = "bs_tierlimitamount";
			public const string bs_TotalDueToOwner = "bs_totalduetoowner";
			public const string bs_TotalDueToTownePark = "bs_totalduetotownepark";
			public const string bs_Year = "bs_year";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_ProfitShareByPercentage_BillingStatement = "bs_ProfitShareByPercentage_BillingStatement";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_ProfitShareByPercentage() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_profitsharebypercentage";
		
		public const string EntityLogicalCollectionName = "bs_profitsharebypercentages";
		
		public const string EntitySetName = "bs_profitsharebypercentages";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingstatementfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_BillingStatementFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_billingstatementfk");
			}
			set
			{
				this.SetAttributeValue("bs_billingstatementfk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_month")]
		public string bs_Month
		{
			get
			{
				return this.GetAttributeValue<string>("bs_month");
			}
			set
			{
				this.SetAttributeValue("bs_month", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_ownerpercent")]
		public System.Nullable<double> bs_OwnerPercent
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("bs_ownerpercent");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_ownerpercentdisplay")]
		public string bs_OwnerPercentDisplay
		{
			get
			{
				return this.GetAttributeValue<string>("bs_ownerpercentdisplay");
			}
			set
			{
				this.SetAttributeValue("bs_ownerpercentdisplay", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_percenttocharge")]
		public System.Nullable<double> bs_PercentToCharge
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("bs_percenttocharge");
			}
			set
			{
				this.SetAttributeValue("bs_percenttocharge", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitamount")]
		public System.Nullable<double> bs_ProfitAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("bs_profitamount");
			}
			set
			{
				this.SetAttributeValue("bs_profitamount", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitsharebypercentageid")]
		public System.Nullable<System.Guid> bs_ProfitShareByPercentageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_profitsharebypercentageid");
			}
			set
			{
				this.SetAttributeValue("bs_profitsharebypercentageid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_profitsharebypercentageid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_ProfitShareByPercentageId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_site")]
		public string bs_Site
		{
			get
			{
				return this.GetAttributeValue<string>("bs_site");
			}
			set
			{
				this.SetAttributeValue("bs_site", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_tierlimitamount")]
		public string bs_TierLimitAmount
		{
			get
			{
				return this.GetAttributeValue<string>("bs_tierlimitamount");
			}
			set
			{
				this.SetAttributeValue("bs_tierlimitamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_totalduetoowner")]
		public System.Nullable<double> bs_TotalDueToOwner
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("bs_totalduetoowner");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_totalduetotownepark")]
		public System.Nullable<double> bs_TotalDueToTownePark
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("bs_totalduetotownepark");
			}
			set
			{
				this.SetAttributeValue("bs_totalduetotownepark", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_year")]
		public string bs_Year
		{
			get
			{
				return this.GetAttributeValue<string>("bs_year");
			}
			set
			{
				this.SetAttributeValue("bs_year", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Profit Share By Percentage
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_profitsharebypercentage_statecode? statecode
		{
			get
			{
				return ((bs_profitsharebypercentage_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Profit Share By Percentage
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_profitsharebypercentage_statuscode? statuscode
		{
			get
			{
				return ((bs_profitsharebypercentage_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_ProfitShareByPercentage_BillingStatement
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingstatementfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_ProfitShareByPercentage_BillingStatement")]
		public TownePark.bs_BillingStatement bs_ProfitShareByPercentage_BillingStatement
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_BillingStatement>("bs_ProfitShareByPercentage_BillingStatement", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_BillingStatement>("bs_ProfitShareByPercentage_BillingStatement", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
