#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Payroll Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_payrolldetail_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Payroll Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_payrolldetail_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_payrolldetail")]
	public partial class bs_PayrollDetail : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_payrolldetail entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_Date = "bs_date";
			public const string bs_DisplayName = "bs_displayname";
			public const string bs_ForecastPayrollCost = "bs_forecastpayrollcost";
			public const string bs_ForecastPayrollRevenue = "bs_forecastpayrollrevenue";
			public const string bs_JobCodeFK = "bs_jobcodefk";
			public const string bs_JobGroupFK = "bs_jobgroupfk";
			public const string bs_Name = "bs_name";
			public const string bs_PayrollDetailId = "bs_payrolldetailid";
			public const string Id = "bs_payrolldetailid";
			public const string bs_PayrollFK = "bs_payrollfk";
			public const string bs_RegularHours = "bs_regularhours";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_PayrollDetail_JobCode = "bs_PayrollDetail_JobCode";
			public const string bs_PayrollDetail_JobGroup = "bs_PayrollDetail_JobGroup";
			public const string bs_PayrollDetail_Payroll = "bs_PayrollDetail_Payroll";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_PayrollDetail() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_payrolldetail";
		
		public const string EntityLogicalCollectionName = "bs_payrolldetails";
		
		public const string EntitySetName = "bs_payrolldetails";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_date")]
		public System.Nullable<System.DateTime> bs_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_date");
			}
			set
			{
				this.SetAttributeValue("bs_date", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_displayname")]
		public string bs_DisplayName
		{
			get
			{
				return this.GetAttributeValue<string>("bs_displayname");
			}
			set
			{
				this.SetAttributeValue("bs_displayname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_forecastpayrollcost")]
		public System.Nullable<decimal> bs_ForecastPayrollCost
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_forecastpayrollcost");
			}
			set
			{
				this.SetAttributeValue("bs_forecastpayrollcost", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_forecastpayrollrevenue")]
		public System.Nullable<decimal> bs_ForecastPayrollRevenue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_forecastpayrollrevenue");
			}
			set
			{
				this.SetAttributeValue("bs_forecastpayrollrevenue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_jobcodefk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_JobCodeFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_jobcodefk");
			}
			set
			{
				this.SetAttributeValue("bs_jobcodefk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_jobgroupfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_JobGroupFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_jobgroupfk");
			}
			set
			{
				this.SetAttributeValue("bs_jobgroupfk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolldetailid")]
		public System.Nullable<System.Guid> bs_PayrollDetailId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_payrolldetailid");
			}
			set
			{
				this.SetAttributeValue("bs_payrolldetailid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrolldetailid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_PayrollDetailId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_PayrollFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_payrollfk");
			}
			set
			{
				this.SetAttributeValue("bs_payrollfk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_regularhours")]
		public System.Nullable<decimal> bs_RegularHours
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_regularhours");
			}
			set
			{
				this.SetAttributeValue("bs_regularhours", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Payroll Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_payrolldetail_statecode? statecode
		{
			get
			{
				return ((bs_payrolldetail_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Payroll Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_payrolldetail_statuscode? statuscode
		{
			get
			{
				return ((bs_payrolldetail_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_PayrollDetail_JobCode
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_jobcodefk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_PayrollDetail_JobCode")]
		public TownePark.bs_JobCode bs_PayrollDetail_JobCode
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_JobCode>("bs_PayrollDetail_JobCode", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_JobCode>("bs_PayrollDetail_JobCode", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bs_PayrollDetail_JobGroup
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_jobgroupfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_PayrollDetail_JobGroup")]
		public TownePark.bs_JobGroup bs_PayrollDetail_JobGroup
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_JobGroup>("bs_PayrollDetail_JobGroup", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_JobGroup>("bs_PayrollDetail_JobGroup", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bs_PayrollDetail_Payroll
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_payrollfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_PayrollDetail_Payroll")]
		public TownePark.bs_Payroll bs_PayrollDetail_Payroll
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_Payroll>("bs_PayrollDetail_Payroll", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_Payroll>("bs_PayrollDetail_Payroll", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
