#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Revenue Share Threshold
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_revenuesharethreshold_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Revenue Share Threshold
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_revenuesharethreshold_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_revenuesharethreshold")]
	public partial class bs_RevenueShareThreshold : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_revenuesharethreshold entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_Contract = "bs_contract";
			public const string bs_InvoiceGroup = "bs_invoicegroup";
			public const string bs_Name = "bs_name";
			public const string bs_RevenueAccumulationType = "bs_revenueaccumulationtype";
			public const string bs_RevenueCodeData = "bs_revenuecodedata";
			public const string bs_RevenueShareThresholdId = "bs_revenuesharethresholdid";
			public const string Id = "bs_revenuesharethresholdid";
			public const string bs_TierData = "bs_tierdata";
			public const string bs_ValidationThresholdAmount = "bs_validationthresholdamount";
			public const string bs_ValidationThresholdType = "bs_validationthresholdtype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_RevenueShareThreshold_Contract = "bs_RevenueShareThreshold_Contract";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_RevenueShareThreshold() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_revenuesharethreshold";
		
		public const string EntityLogicalCollectionName = "bs_revenuesharethresholds";
		
		public const string EntitySetName = "bs_revenuesharethresholds";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contract")]
		public Microsoft.Xrm.Sdk.EntityReference bs_Contract
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_contract");
			}
			set
			{
				this.SetAttributeValue("bs_contract", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_invoicegroup")]
		public System.Nullable<int> bs_InvoiceGroup
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bs_invoicegroup");
			}
			set
			{
				this.SetAttributeValue("bs_invoicegroup", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_revenueaccumulationtype")]
		public virtual bs_revenueaccumulationtype? bs_RevenueAccumulationType
		{
			get
			{
				return ((bs_revenueaccumulationtype?)(EntityOptionSetEnum.GetEnum(this, "bs_revenueaccumulationtype")));
			}
			set
			{
				this.SetAttributeValue("bs_revenueaccumulationtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// JSON representation of a Threshold Structure's applicable Revenue Codes
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_revenuecodedata")]
		public string bs_RevenueCodeData
		{
			get
			{
				return this.GetAttributeValue<string>("bs_revenuecodedata");
			}
			set
			{
				this.SetAttributeValue("bs_revenuecodedata", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_revenuesharethresholdid")]
		public System.Nullable<System.Guid> bs_RevenueShareThresholdId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_revenuesharethresholdid");
			}
			set
			{
				this.SetAttributeValue("bs_revenuesharethresholdid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_revenuesharethresholdid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_RevenueShareThresholdId = value;
			}
		}
		
		/// <summary>
		/// JSON representation of Revenue Share threshold tiers
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_tierdata")]
		public string bs_TierData
		{
			get
			{
				return this.GetAttributeValue<string>("bs_tierdata");
			}
			set
			{
				this.SetAttributeValue("bs_tierdata", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_validationthresholdamount")]
		public System.Nullable<decimal> bs_ValidationThresholdAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_validationthresholdamount");
			}
			set
			{
				this.SetAttributeValue("bs_validationthresholdamount", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_validationthresholdtype")]
		public virtual bs_validationthresholdtype? bs_ValidationThresholdType
		{
			get
			{
				return ((bs_validationthresholdtype?)(EntityOptionSetEnum.GetEnum(this, "bs_validationthresholdtype")));
			}
			set
			{
				this.SetAttributeValue("bs_validationthresholdtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Revenue Share Threshold
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_revenuesharethreshold_statecode? statecode
		{
			get
			{
				return ((bs_revenuesharethreshold_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Revenue Share Threshold
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_revenuesharethreshold_statuscode? statuscode
		{
			get
			{
				return ((bs_revenuesharethreshold_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_RevenueShareThreshold_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_contract")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_RevenueShareThreshold_Contract")]
		public TownePark.bs_Contract bs_RevenueShareThreshold_Contract
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_Contract>("bs_RevenueShareThreshold_Contract", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_Contract>("bs_RevenueShareThreshold_Contract", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
