#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the Site Statistic Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_sitestatisticdetail_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Site Statistic Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_sitestatisticdetail_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bs_sitestatisticdetail")]
	public partial class bs_SiteStatisticDetail : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bs_sitestatisticdetail entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_AdjustmentPercentage = "bs_adjustmentpercentage";
			public const string bs_AdjustmentValue = "bs_adjustmentvalue";
			public const string bs_BaseRevenue = "bs_baserevenue";
			public const string bs_CaptureRatio = "bs_captureratio";
			public const string bs_Date = "bs_date";
			public const string bs_DriveInRatio = "bs_driveinratio";
			public const string bs_ExternalRevenue = "bs_externalrevenue";
			public const string bs_Name = "bs_name";
			public const string bs_Occupancy = "bs_occupancy";
			public const string bs_OccupiedRooms = "bs_occupiedrooms";
			public const string bs_SelfAggregator = "bs_selfaggregator";
			public const string bs_SelfComps = "bs_selfcomps";
			public const string bs_SelfDaily = "bs_selfdaily";
			public const string bs_SelfMonthly = "bs_selfmonthly";
			public const string bs_SelfOvernight = "bs_selfovernight";
			public const string bs_SelfRateDaily = "bs_selfratedaily";
			public const string bs_SelfRateMonthly = "bs_selfratemonthly";
			public const string bs_SiteStatisticDetailId = "bs_sitestatisticdetailid";
			public const string Id = "bs_sitestatisticdetailid";
			public const string bs_SiteStatisticFK = "bs_sitestatisticfk";
			public const string bs_Type = "bs_type";
			public const string bs_ValetAggregator = "bs_valetaggregator";
			public const string bs_ValetComps = "bs_valetcomps";
			public const string bs_ValetDaily = "bs_valetdaily";
			public const string bs_ValetMonthly = "bs_valetmonthly";
			public const string bs_ValetOvernight = "bs_valetovernight";
			public const string bs_ValetRateDaily = "bs_valetratedaily";
			public const string bs_ValetRateMonthly = "bs_valetratemonthly";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_SiteStatistic_SiteStatisticDetail = "bs_SiteStatistic_SiteStatisticDetail";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bs_SiteStatisticDetail() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bs_sitestatisticdetail";
		
		public const string EntityLogicalCollectionName = "bs_sitestatisticdetails";
		
		public const string EntitySetName = "bs_sitestatisticdetails";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_adjustmentpercentage")]
		public System.Nullable<decimal> bs_AdjustmentPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_adjustmentpercentage");
			}
			set
			{
				this.SetAttributeValue("bs_adjustmentpercentage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_adjustmentvalue")]
		public System.Nullable<decimal> bs_AdjustmentValue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_adjustmentvalue");
			}
			set
			{
				this.SetAttributeValue("bs_adjustmentvalue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_baserevenue")]
		public System.Nullable<decimal> bs_BaseRevenue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_baserevenue");
			}
			set
			{
				this.SetAttributeValue("bs_baserevenue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_captureratio")]
		public System.Nullable<decimal> bs_CaptureRatio
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_captureratio");
			}
			set
			{
				this.SetAttributeValue("bs_captureratio", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_date")]
		public System.Nullable<System.DateTime> bs_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bs_date");
			}
			set
			{
				this.SetAttributeValue("bs_date", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_driveinratio")]
		public System.Nullable<decimal> bs_DriveInRatio
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_driveinratio");
			}
			set
			{
				this.SetAttributeValue("bs_driveinratio", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_externalrevenue")]
		public System.Nullable<decimal> bs_ExternalRevenue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_externalrevenue");
			}
			set
			{
				this.SetAttributeValue("bs_externalrevenue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_name")]
		public string bs_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bs_name");
			}
			set
			{
				this.SetAttributeValue("bs_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_occupancy")]
		public System.Nullable<decimal> bs_Occupancy
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_occupancy");
			}
			set
			{
				this.SetAttributeValue("bs_occupancy", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_occupiedrooms")]
		public System.Nullable<decimal> bs_OccupiedRooms
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_occupiedrooms");
			}
			set
			{
				this.SetAttributeValue("bs_occupiedrooms", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_selfaggregator")]
		public System.Nullable<decimal> bs_SelfAggregator
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_selfaggregator");
			}
			set
			{
				this.SetAttributeValue("bs_selfaggregator", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_selfcomps")]
		public System.Nullable<decimal> bs_SelfComps
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_selfcomps");
			}
			set
			{
				this.SetAttributeValue("bs_selfcomps", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_selfdaily")]
		public System.Nullable<decimal> bs_SelfDaily
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_selfdaily");
			}
			set
			{
				this.SetAttributeValue("bs_selfdaily", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_selfmonthly")]
		public System.Nullable<decimal> bs_SelfMonthly
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_selfmonthly");
			}
			set
			{
				this.SetAttributeValue("bs_selfmonthly", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_selfovernight")]
		public System.Nullable<decimal> bs_SelfOvernight
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_selfovernight");
			}
			set
			{
				this.SetAttributeValue("bs_selfovernight", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_selfratedaily")]
		public System.Nullable<decimal> bs_SelfRateDaily
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_selfratedaily");
			}
			set
			{
				this.SetAttributeValue("bs_selfratedaily", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_selfratemonthly")]
		public System.Nullable<decimal> bs_SelfRateMonthly
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_selfratemonthly");
			}
			set
			{
				this.SetAttributeValue("bs_selfratemonthly", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitestatisticdetailid")]
		public System.Nullable<System.Guid> bs_SiteStatisticDetailId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bs_sitestatisticdetailid");
			}
			set
			{
				this.SetAttributeValue("bs_sitestatisticdetailid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitestatisticdetailid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bs_SiteStatisticDetailId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitestatisticfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_SiteStatisticFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_sitestatisticfk");
			}
			set
			{
				this.SetAttributeValue("bs_sitestatisticfk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_type")]
		public virtual bs_sitestatisticdetailchoice? bs_Type
		{
			get
			{
				return ((bs_sitestatisticdetailchoice?)(EntityOptionSetEnum.GetEnum(this, "bs_type")));
			}
			set
			{
				this.SetAttributeValue("bs_type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_valetaggregator")]
		public System.Nullable<decimal> bs_ValetAggregator
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_valetaggregator");
			}
			set
			{
				this.SetAttributeValue("bs_valetaggregator", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_valetcomps")]
		public System.Nullable<decimal> bs_ValetComps
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_valetcomps");
			}
			set
			{
				this.SetAttributeValue("bs_valetcomps", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_valetdaily")]
		public System.Nullable<decimal> bs_ValetDaily
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_valetdaily");
			}
			set
			{
				this.SetAttributeValue("bs_valetdaily", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_valetmonthly")]
		public System.Nullable<decimal> bs_ValetMonthly
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_valetmonthly");
			}
			set
			{
				this.SetAttributeValue("bs_valetmonthly", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_valetovernight")]
		public System.Nullable<decimal> bs_ValetOvernight
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_valetovernight");
			}
			set
			{
				this.SetAttributeValue("bs_valetovernight", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_valetratedaily")]
		public System.Nullable<decimal> bs_ValetRateDaily
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_valetratedaily");
			}
			set
			{
				this.SetAttributeValue("bs_valetratedaily", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_valetratemonthly")]
		public System.Nullable<decimal> bs_ValetRateMonthly
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bs_valetratemonthly");
			}
			set
			{
				this.SetAttributeValue("bs_valetratemonthly", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Site Statistic Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bs_sitestatisticdetail_statecode? statecode
		{
			get
			{
				return ((bs_sitestatisticdetail_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Site Statistic Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bs_sitestatisticdetail_statuscode? statuscode
		{
			get
			{
				return ((bs_sitestatisticdetail_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_SiteStatistic_SiteStatisticDetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_sitestatisticfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_SiteStatistic_SiteStatisticDetail")]
		public TownePark.bs_SiteStatistic bs_SiteStatistic_SiteStatisticDetail
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_SiteStatistic>("bs_SiteStatistic_SiteStatisticDetail", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_SiteStatistic>("bs_SiteStatistic_SiteStatisticDetail", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
