#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Status of the ReadyForInvoice
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr9e8_readyforinvoice_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the ReadyForInvoice
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr9e8_readyforinvoice_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// This table contains information ready for invoicing
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cr9e8_readyforinvoice")]
	public partial class cr9e8_readyforinvoice : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the cr9e8_readyforinvoice entity
		/// </summary>
		public partial class Fields
		{
			public const string bs_BillingStatementFK = "bs_billingstatementfk";
			public const string bs_CustomerSiteFK = "bs_customersitefk";
			public const string cr9e8_comments = "cr9e8_comments";
			public const string cr9e8_invoicestatus = "cr9e8_invoicestatus";
			public const string cr9e8_period = "cr9e8_period";
			public const string cr9e8_readyforinvoiceId = "cr9e8_readyforinvoiceid";
			public const string Id = "cr9e8_readyforinvoiceid";
			public const string cr9e8_rssfile = "cr9e8_rssfile";
			public const string cr9e8_site = "cr9e8_site";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bs_BillingStatement_cr9e8_readyforinvoice = "bs_BillingStatement_cr9e8_readyforinvoice";
			public const string bs_CustomerSite_cr9e8_readyforinvoice = "bs_CustomerSite_cr9e8_readyforinvoice";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public cr9e8_readyforinvoice() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "cr9e8_readyforinvoice";
		
		public const string EntityLogicalCollectionName = "cr9e8_readyforinvoices";
		
		public const string EntitySetName = "cr9e8_readyforinvoices";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingstatementfk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_BillingStatementFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_billingstatementfk");
			}
			set
			{
				this.SetAttributeValue("bs_billingstatementfk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		public Microsoft.Xrm.Sdk.EntityReference bs_CustomerSiteFK
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bs_customersitefk");
			}
			set
			{
				this.SetAttributeValue("bs_customersitefk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr9e8_comments")]
		public string cr9e8_comments
		{
			get
			{
				return this.GetAttributeValue<string>("cr9e8_comments");
			}
			set
			{
				this.SetAttributeValue("cr9e8_comments", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr9e8_invoicestatus")]
		public string cr9e8_invoicestatus
		{
			get
			{
				return this.GetAttributeValue<string>("cr9e8_invoicestatus");
			}
			set
			{
				this.SetAttributeValue("cr9e8_invoicestatus", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr9e8_period")]
		public string cr9e8_period
		{
			get
			{
				return this.GetAttributeValue<string>("cr9e8_period");
			}
			set
			{
				this.SetAttributeValue("cr9e8_period", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr9e8_readyforinvoiceid")]
		public System.Nullable<System.Guid> cr9e8_readyforinvoiceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("cr9e8_readyforinvoiceid");
			}
			set
			{
				this.SetAttributeValue("cr9e8_readyforinvoiceid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr9e8_readyforinvoiceid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.cr9e8_readyforinvoiceId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr9e8_rssfile")]
		public string cr9e8_rssfile
		{
			get
			{
				return this.GetAttributeValue<string>("cr9e8_rssfile");
			}
			set
			{
				this.SetAttributeValue("cr9e8_rssfile", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr9e8_site")]
		public string cr9e8_site
		{
			get
			{
				return this.GetAttributeValue<string>("cr9e8_site");
			}
			set
			{
				this.SetAttributeValue("cr9e8_site", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the ReadyForInvoice
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual cr9e8_readyforinvoice_statecode? statecode
		{
			get
			{
				return ((cr9e8_readyforinvoice_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the ReadyForInvoice
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual cr9e8_readyforinvoice_statuscode? statuscode
		{
			get
			{
				return ((cr9e8_readyforinvoice_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bs_BillingStatement_cr9e8_readyforinvoice
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_billingstatementfk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_BillingStatement_cr9e8_readyforinvoice")]
		public TownePark.bs_BillingStatement bs_BillingStatement_cr9e8_readyforinvoice
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_BillingStatement>("bs_BillingStatement_cr9e8_readyforinvoice", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_BillingStatement>("bs_BillingStatement_cr9e8_readyforinvoice", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bs_CustomerSite_cr9e8_readyforinvoice
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bs_customersitefk")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bs_CustomerSite_cr9e8_readyforinvoice")]
		public TownePark.bs_CustomerSite bs_CustomerSite_cr9e8_readyforinvoice
		{
			get
			{
				return this.GetRelatedEntity<TownePark.bs_CustomerSite>("bs_CustomerSite_cr9e8_readyforinvoice", null);
			}
			set
			{
				this.SetRelatedEntity<TownePark.bs_CustomerSite>("bs_CustomerSite_cr9e8_readyforinvoice", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
