#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_billingstatementstatuschoices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GENERATING = 126840000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NEEDS_REVIEW = 126840001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		APPROVED = 126840002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SENT = 126840003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AR_REVIEW = 126840004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		APPROVAL_TEAM = 126840005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		READY_TO_SEND = 126840006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FAILED = 126840007,
	}
}
#pragma warning restore CS1591
