#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	/// <summary>
	/// Type of contracts to choose from
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_contracttypechoices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FixedFee = 126840000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerLaborHour = 126840001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerOccupiedRoom = 126840002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvoiceGrouping = 126840003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RevenueShare = 126840004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BellService = 126840005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MidMonthAdvance = 126840006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DepositedRevenue = 126840007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BillingAccount = 126840008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagementAgreement = 126840009,
	}
}
#pragma warning restore CS1591
