#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_glcodetypechoices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonGLBillableExpense = 126840015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonBillableExpense = 126840014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Service = 126840000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonSalariedJob = 126840001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClientPaidExpense = 126840002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReimbursableExpense = 126840003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MiscellaneousItem = 126840004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerOccupiedRoom = 126840005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RevenueShare = 126840006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagementAgreement = 126840007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BellServiceFee = 126840008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalariedJob = 126840009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RateAndFeeData = 126840010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RevenueCode = 126840011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PayrollAccount = 126840012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExpenseAccount = 126840013,
	}
}
#pragma warning restore CS1591
