#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_generalconfigchoices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TowneParksAddress = 126840000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TowneParksPhone = 126840001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TowneParksLegalName = 126840002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TowneParksPOBox = 126840003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TowneParksAccountNumber = 126840004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TowneParksABA = 126840005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TowneParksEmail = 126840006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UPPGlobalLegalName = 126840007,
	}
}
#pragma warning restore CS1591
