#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_profitshareaccumulationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monthly = 126840000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnnualCalendar = 126840001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnnualAnniversary = 126840002,
	}
}
#pragma warning restore CS1591
