#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_ratecategorytypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValetOvernight = 126840000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SelfOvernight = 126840001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValetDaily = 126840002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SelfDaily = 126840003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValetMonthly = 126840004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SelfMonthly = 126840005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValetAggregator = 126840006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SelfAggregator = 126840007,
	}
}
#pragma warning restore CS1591
