#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownePark
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bs_supportingreporttypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MixOfSales = 126840000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HoursBackupReport = 126840001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaxReport = 126840002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LaborDistributionReport = 126840003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherExpensesReport = 126840004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ParkingDepartmentReport = 126840005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ValidationReport = 126840006,
	}
}
#pragma warning restore CS1591
